### ISSUE TITLE
Error executing BTOR backend

### ISSUE THREAD

**Issue by yangy96** [YosysHQ/yosys#1037]
## Steps to reproduce the issue

File: [issue_design.tar.gz](https://github.com/YosysHQ/yosys/files/3214289/issue_design.tar.gz)

```
tar -xf issue_design.tar.gz  
cd issue_design 
yosys -s commands.ys
```

## Expected behavior
Execute btor backend of the design successfully. 

## Actual behavior
When the program tried to execute BTOR backend,  it found the error saying  “Assert `cell_recursion_guard.count(cell) == 0' failed in backends/btor/btor.cc:132.” . 

I tried to solve the problem and found the wire `csr_cmd` (line 129 in vscale_pipeline.v) may cause the error. This wire is the output from ctrl module and the input of the csr_file module. 
The wire is implemented as following in ctrl module (line 412 in vscale_ctrl.v):  
```csr_cmd = (kill_DX) ? `CSR_IDLE : csr_cmd_unkilled; ```  If I comment this line or change the line to  ``` assign csr_cmd = `CSR_IDLE ``` or  ``` assign csr_cmd = csr_cmd_unkilled ```, yosys could execute BTOR backend successfully. If I want to make csr_cmd dependent on kill_DX, I will get the same error. 

##
Please let me know if I can provide more information! Thank you for your help and all your work on Yosys!

**Comment by cliffordwolf** [comment]
> If I want to make csr_cmd dependent on kill_DX, I will get the same error.

That's because `kill_DX` (at least topologically) depends on `csr_cmd`:

```
csr.cmd
=> csr.illegal_acces
=> csr.new_ex_DX
=> csr.ex_DX
=> ctrl.kill_DX
```

Therefore using `ctrl.kill_DX` in the expression for `csr.cmd` causes a logic loop.

(There also a 2nd slightly larger loop with `csr.ex_DX => ctrl.stall_DX => ctrl.kill_DX`.)

I've added a proper error message for this case in b7dd7c2. Now your example will produce the following output:

```25. Executing BTOR backend.
ERROR: Found topological loop while processing cell $techmap\ctrl.$logic_or$vscale_ctrl.v:160$113. Active cells:
    $techmap\ctrl.$ternary$vscale_ctrl.v:412$187
    $techmap\csr.$logic_or$vscale_csr_file.v:99$21
    $techmap\csr.$logic_and$vscale_csr_file.v:102$24
    $techmap\csr.$logic_or$vscale_csr_file.v:103$27
    $techmap\csr.$logic_or$vscale_csr_file.v:105$30
    $techmap\ctrl.$logic_or$vscale_ctrl.v:168$127
    $techmap\ctrl.$logic_or$vscale_ctrl.v:169$128
    $techmap\ctrl.$logic_or$vscale_ctrl.v:167$120
    $techmap\ctrl.$logic_or$vscale_ctrl.v:167$121
    $techmap\ctrl.$logic_not$vscale_ctrl.v:167$122
    $techmap\ctrl.$logic_and$vscale_ctrl.v:167$123
    $techmap\ctrl.$logic_or$vscale_ctrl.v:167$124
    $techmap\ctrl.$logic_or$vscale_ctrl.v:160$111
    $techmap\ctrl.$logic_or$vscale_ctrl.v:160$112
    $techmap\ctrl.$logic_or$vscale_ctrl.v:160$113
    $techmap\ctrl.$logic_not$vscale_ctrl.v:403$168
    $techmap\ctrl.$logic_and$vscale_ctrl.v:407$177
```
