### ISSUE TITLE
Incorrect error message is reported in case when non-existent module was specified for fmcombine command.

### ISSUE THREAD

**Issue by SergeyDegtyar** [YosysHQ/yosys#1063]
## Steps to reproduce the issue
**test case:**
module top
(
 input x,
 input y,
 input cin,

 output reg A,
 output cout
 );
 parameter X = 1;
 wire o;

always @(posedge cin)
	A <= o;

assign cout =  cin? y : x;

middle u_mid1 (.x(x),.o(o),.y(1'b0));
middle u_mid2 (.x(x),.o(o),.y(1'b1));
middle u_mid3 (.x(x),.o(o),.y(1'bX));
middle u_mid4 (.x(x),.o(o),.y(1'bX));

endmodule

module middle
(
	input x,
	input y,
	output o
);

urtl u_urtl (.x(x),.o(o),.y(y));
endmodule

module urtl
(
	input x,
	input y,
	output o
);

assign o = x + y;
endmodule

**script:**
read_verilog top.v
proc
fmcombine top u_mid1 u_mid8

## Expected behavior

*ERROR: Gate cell u_mid8 not found in module top.*

## Actual behavior

*ERROR: Gold cell u_mid8 not found in module top.*

**This bug is also actual for other message reported for gate cell: "Gold cell has unresolved instance parameters."**

**Comment by cliffordwolf** [comment]
Oops. Thanks! Fixed.
