### ISSUE TITLE
ERROR: Abort in passes/techmap/extract_fa.cc:218

### ISSUE THREAD

**Issue by ZirconiumX** [YosysHQ/yosys#1099]
## Steps to reproduce the issue

Using [picorv32.zip](https://github.com/YosysHQ/yosys/files/3294223/picorv32.zip), run `yosys -p "synth; extract_fa" picorv32.v`.

Reproducible on a3a80b75 and latest master d4f77d40.

## Expected behavior

Perhaps a more detailed error message? I realise this is probably stupid of me, but asking in #yosys said I should report calls to `log_abort` anyway.

## Actual behavior

```
3. Executing EXTRACT_FA pass (find and extract full/half adders).
Extracting full/half adders from $paramod$4d2dfdcc1db1a7362453fb449ccdda75bb1b39f9\picorv32:
ERROR: Abort in passes/techmap/extract_fa.cc:218.
```

**Comment by eddiehung** [comment]
Appreciate the effort you've taken to report it @ZirconiumX! I've proposed a fix in #1190 which replaces the `log_abort()` with more grace -- it doesn't print any warning messages, but behaves just as if it couldn't find any full adders anyway.
