### ISSUE TITLE
An incorrect error message is reported by the shregmap command in the case with a combination of exclusive options

### ISSUE THREAD

**Issue by SergeyDegtyar** [YosysHQ/yosys#1113]
## Steps to reproduce the issue

test case:
```
module top    (
out,
clk,
in
);
    output [7:0] out;
    input clk, in;
    reg [7:0] out;

    always @(posedge clk)
	begin
`ifndef BUG
		out    <= out << 1;
		out[0] <= in;
`else
	out <= 8'bZZZZZZZZ;
`endif
	end

endmodule
```
script:
`shregmap -tech greenpak4 -match -enpol pos`
or
`shregmap -tech greenpak4 -match -params`

## Expected behavior

yosys> shregmap -tech greenpak4 -match -enpol pos

24. Executing SHREGMAP pass (map shift registers).
ERROR: Options **-enpol** and -match are exclusive!

yosys> shregmap -tech greenpak4 -match -params

25. Executing SHREGMAP pass (map shift registers).
ERROR: Options **-params** and -match are exclusive!

## Actual behavior

yosys> shregmap -tech greenpak4 -match -enpol pos

24. Executing SHREGMAP pass (map shift registers).
ERROR: Options **-clkpol** and -match are exclusive!

yosys> shregmap -tech greenpak4 -match -params

25. Executing SHREGMAP pass (map shift registers).
ERROR: Options **-clkpol** and -match are exclusive!

**Comment by cliffordwolf** [comment]
Hmm... `-tech greenpak4` implies `-clkpol pos` and `-zinit`, which explains why there's an error about `-clkpol` and `-match`. I'll update the `shregmap` help message accordingly.
