### ISSUE TITLE
RFC: Ignore SIGINT in interactive mode

### ISSUE THREAD

**Issue by bwidawsk** [YosysHQ/yosys#1157]
Since the yosys interpreter behaves a lot like a shell, and many people have a habit of using ctrl-c to abort the current command, it seems to be a common occurrence for accidentally aborting the interpreter and losing work.

This RFC proposes that SIGINT is blocked by yosys, perhaps state-fully (in that a second ctrl-c will abort). Instead ctrl-d, or the exit command would be required (or SIGKILL) to end the interpreter.

**Comment by eddiehung** [comment]
A very reasonable request @bwidawsk! 
In Python, Ctrl+C is caught, but Ctrl+D is what actually exits. Would you be up for giving it a go and PR it?

**Comment by bwidawsk** [comment]
Yeah, I'm happy to give it a shot.

On 19-07-08 18:51:17, Eddie Hung wrote:
> A very reasonable request @bwidawsk!
> In Python, Ctrl+C is caught, but Ctrl+D is what actually exits. Would you be up
> for giving it a go and PR it?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Ben Widawsky, Intel Open Source Technology Center
