### ISSUE TITLE
Conflicting default_nettype statements

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#1217]
## Steps to reproduce the issue

Using the following code:
```
`default_nettype none
module mcve2(david);
	output	reg	david;

	always @(*)
		goliath = 4;

	always @(*)
		david = goliath;
endmodule
`default_nettype wire
```

If `default_nettype wire` is specified at the top, a wire for goliath should be quietly created.  If `default_nettype none` is specified at the top, the design should fail since goliath has not been declared.

## Expected behavior

  In this particular case, with the declaration of `default_nettype none` at the top followed by `default_nettype wire`, the file should be treated as though `default_nettype none` were set, which should cause Yosys to exit with an error when encountering the undefined `goliath`.

## Actual behavior

However, because the `default_nettype wire` at the end, it appears to be overriding the `default_nettype none` from earlier.  As a result, `goliath` is implicitly declared.

**Comment by clairexen** [comment]
See #3125
