### ISSUE TITLE
Add an optional step in synth_xilinx to insert I/O buffers.

### ISSUE THREAD

**Issue by koriakin** [YosysHQ/yosys#1235]
This is needed by the ISE flow.  Requirements:

1. Add IBUFs on top-level inputs
  1.1. Make it IBUFGs if routed to BUFG* or DCM/PLL/MMCM?
2. Add OBUFs on top-level outputs
3. Add OBUFTs on top-level outputs with tristate
4. Add IOBUFs on top-level inputs+outputs with tristate
5. Skip buffer insertion if the top-level pin is already connected to a suitable buffer

**Comment by koriakin** [comment]
I suggest `-iopads`

**Comment by eddiehung** [comment]
Can requirements 1, 2, 5 considered fixed by #1292?

**Comment by koriakin** [comment]
Yes, we're only missing tristate now.

**Comment by eddiehung** [comment]
Okay, closing. Let's use #1225 to track tristate.
