### ISSUE TITLE
Multiple drivers in carry cell

### ISSUE THREAD

**Issue by olofk** [YosysHQ/yosys#1265]
After upgrading yosys to 0.8+634 (e9a756aa) from a version built some time in March 2019 I'm getting

    ERROR: multiple drivers on net 'CO' (carry.CO and $logic_or$/usr/local/bin/../share/yosys/ice40/cells_sim.v:141$8.Y)

in nextpnr. Example design [servant_0.tar.gz](https://github.com/YosysHQ/yosys/files/3478830/servant_0.tar.gz)

To reproduce

    make -C servant_0/tinyfpga_bx-icestorm

**Comment by daveshah1** [comment]
If your version of nextpnr is from before late June, you will need to update to cope with the new whitebox support in Yosys.

**Comment by olofk** [comment]
Ah ok. I'll do that. Is there any particular order I need to compile the tools (yosys, nextpnr, icestorm) or is it just enough to update and rebuild nexpnr?

**Comment by daveshah1** [comment]
If you haven't updated for a while, it would be a good idea to update icestorm first (as nextpnr uses icestorm to build its database), although I don't think there have been any significant changes in the last few months.

**Comment by olofk** [comment]
Updating nextpnr worked fine with the added benefit of raising Fmax almost 30%. Thanks
