### ISSUE TITLE
muxcover behavior change

### ISSUE THREAD

**Issue by mmicko** [YosysHQ/yosys#1273]
## Steps to reproduce the issue
```
module top (
    input [5:0] S,
    input [63:0] D,
    output M256
);
    assign M256 = D[S];
endmodule
```

```
yosys -p 'read_verilog top.v ; synth -top top ; muxcover -mux8; stat'
```

## Expected behavior
```
   Number of cells:                  9
     $_MUX8_                         9
```
## Actual behavior
Behavior changed after https://github.com/YosysHQ/yosys/commit/023086bd46bc828621ebb171b159efe1398aaecf

```
   Number of cells:                 15
     $_MUX8_                         8
     $_MUX_                          4
     $_NMUX_                         3
```

**Comment by cliffordwolf** [comment]
Oops.

I think maybe we should remove `NMUX` and also `AOI3, OAI3, AOI4, OAI4` from the default gate library used when no `-g` option is proved, and add `-g all` for the current behavior.
