### ISSUE TITLE
Bit select of loop variable fails

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#1372]
## Steps to reproduce the issue

Consider the attached file(s).  It contains two methods for calculating a value based upon an input.  The original method (in the FORMAL section) calculates the new answer based directly upon the input.  The updated method uses a lookup table.  In the lookup table generation, there's an `if` that depends upon a bit-select of the loop index.  If used, the two pieces of code are not equivalent.

```
always @(*) begin for(k=0; k<128; k=k+1) begin
  newv = 0;
  if (k[6]) // this line fails, in the attached it is surrounded by a BROKEN_CODE ifdef
    newv = 7'h0a;
  else
    newv = k;
// ...
```
## Expected behavior

I expect the two behaviors, both with `BROKEN_CODE` defined and without, to generate the same code.

## Actual behavior

The code is different.

[mcvesix.zip](https://github.com/YosysHQ/yosys/files/3602986/mcvesix.zip)

**Comment by cliffordwolf** [comment]
My MCVE:
```
module  test (output reg [3:0] out);
        integer k;
        initial begin
                out = 0;
                for(k=0; k<16; k=k+1)
                        if (k[0]) out = out + 1;
        end
endmodule
```
