### ISSUE TITLE
Question: How to use connect for concatenation?

### ISSUE THREAD

**Issue by Kmanfi** [YosysHQ/yosys#1383]
## Steps to reproduce the issue

```
add -input in_foo 2
add -wire w_foo 2
connect -set in_foo w_foo
```
Above works fine but how to connect single wires in design to wire w_foo?

`connect -set w_foo {\_20_, \_21_}
`
## Expected behavior
Works
## Actual behavior
```
ERROR: Failed to parse set rhs expression `{\_20_,'.
```

**Comment by cliffordwolf** [comment]
Concatenations are written as comma separated list with no whitespace in it. And individual bits are written with square brackets. For example:

```
add -mod test
cd test
add -input A 3
add -input B 5
add -output Y 8
connect -set Y A[0],B,A[2:1]
opt_clean
write_verilog
```

This will produce the following output:

```
module test(A, B, Y);
  input [2:0] A;
  input [4:0] B;
  output [7:0] Y;
  assign Y = { A[0], B, A[2:1] };
endmodule
```

(I've just added `add -mod` in `1f64b34` now.)
