### ISSUE TITLE
Reopen #1014

### ISSUE THREAD

**Issue by Kmanfi** [YosysHQ/yosys#1403]
Please reopen
#1014 
There is a  new comment and better test case.

**Comment by koriakin** [comment]
I have no idea where you got your yosys from (I cannot see commit 40cd3841 anywhere in history), but your example works on current master (057dae4f78ef604964fb12175f5b263bb386da24).

Also, please don't file new bugs to reopen old bugs, just reopen them...

**Comment by koriakin** [comment]
Ugh, it seems you cannot actually reopen issues on github, nevermind then — sorry :(

**Comment by daveshah1** [comment]
Never noticed that one before. Seems if you are not an admin you can only reopen issues you created and closed; not issues you created but were closed by someone else.
