### ISSUE TITLE
saw your risc-v post in indiegogo

### ISSUE THREAD

**Issue by quantrpeter** [YosysHQ/yosys#1471]
want to make contact with you

https://m.facebook.com/mcheung63?ref=bookmarks

**Comment by ZipCPU** [comment]
Feel free to contact us on IRC.  Most of the team is available on Freenode's #yosys IRC channel.

Chat with you there.

**Comment by quantrpeter** [comment]
Do you still doing Risc-V in hong kong. I am forming a team too.
