### ISSUE TITLE
Assert `!lut_gates[breaking_lut].empty()' failed in passes/techmap/flowmap.cc:1273.

### ISSUE THREAD

**Issue by ZirconiumX** [YosysHQ/yosys#1475]
## Steps to reproduce the issue

Using [flowmap_1273.tar.gz](https://github.com/YosysHQ/yosys/files/3806667/flowmap_1273.tar.gz), run `yosys -p "flowmap -maxlut 6 -relax" result-1273.il`.

## Expected behavior

`flowmap` completes successfully.

## Actual behavior

```
2. Executing FLOWMAP pass (pack LUTs with FlowMap-r).
Labeling cells.
Mapped to 1 LUTs with maximum depth 1.

Optimizing area.
Relaxing with depth bound 1.
  Breaking LUT $auto$bugpoint.cc:222:simplify_something$3817 to extract LUT 1'0 (potential -350).
ERROR: Assert `!lut_gates[breaking_lut].empty()' failed in passes/techmap/flowmap.cc:1273.
```

cc @whitequark 

Found this while simplifying #1405.

**Comment by whitequark** [comment]
Hm yeah this one is a bit tricky, I'd have to look closer.
