### ISSUE TITLE
wreduce should strip bottom const-0 bits in $mul inputs

### ISSUE THREAD

**Issue by mwkmwkmwk** [YosysHQ/yosys#1500]
Basically: `{A, 2'b00} * B` should be changed to `{A * B, 2'b00}`.  See #1462 for an example where this doesn't happen.  `wreduce` seems like the logical place to do that.

**Comment by cliffordwolf** [comment]
> wreduce seems like the logical place to do that.

I disagree with that point. This is a single-cell optimization pattern. Those are all in `opt_expr`.
