### ISSUE TITLE
Customizing the stat command

### ISSUE THREAD

**Issue by mickey4u** [YosysHQ/yosys#1512]
I am new to yosys. However, I want to find out how to customize the stat command to print only the gate counts to a specified file. Or if there is already a way to do that, can be directed on how to achieve this.

**Comment by daveshah1** [comment]
You can use `tee` to write the output from `stat` to a file. It doesn't support printing just gate counts.

**Comment by mickey4u** [comment]
@daveshah1 I tried `stat tee -a info.txt`, and it printed something other than the stat information.

**Comment by eddiehung** [comment]
`tee`'s help is:
```
yosys> help tee

    tee [-q] [-o logfile|-a logfile] cmd

Execute the specified command, optionally writing the commands output to the
specified logfile(s).

    -q
        Do not print output to the normal destination (console and/or log file).

    -o logfile
        Write output to this file, truncate if exists.

    -a logfile
        Write output to this file, append if exists.

    +INT, -INT
        Add/subtract INT from the -v setting for this command.
```

Thus you would want: `tee -a info.txt stat`

**Comment by mickey4u** [comment]
@eddiehung Thanks
