### ISSUE TITLE
Rolling back commits without doing make clean can trigger classic "No rule to make target" error

### ISSUE THREAD

**Issue by rqou** [YosysHQ/yosys#1692]
## Steps to reproduce the issue

1. Compile a recent version of yosys such as master or commit (7033503cd9e40e16c11fe6c805a436b0e23989dd)
2. Do a git checkout of a very old revision (such as acd8bc0a7496c69864a7dd032eb7f4db7e2e1f2d)
3. Try to compile without doing a make clean

## Expected behavior

Build should succeed

## Actual behavior

```
<snipped>
[ 52%] Building passes/pmgen/ice40_dsp_pm.h
[ 53%] Building passes/pmgen/ice40_dsp.o
[ 53%] Building passes/pmgen/peepopt_pm.h
make: *** No rule to make target 'passes/pmgen/generate.h', needed by 'passes/pmgen/peepopt.o'.  Stop.
```

## Note

I'm pretty sure this is the classic Makefile auto-dependency-generation problem when header files get deleted. I think this can be fixed by using the preprocessor's `-MP` option, but I'm not super familiar with make to try and fix it myself

**Comment by whitequark** [comment]
Fixed by #2357.
