### ISSUE TITLE
Used module read from BLIF removed during synth_ice40

### ISSUE THREAD

**Issue by norandomtechie** [YosysHQ/yosys#1713]
## Steps to reproduce the issue

Given files top.v and ssdec.blif (in [top_ssdec.zip](https://github.com/YosysHQ/yosys/files/4232751/top_ssdec.zip)), we are trying to use synthesize a design using the top module from top.v, which instantiates a module ssdec from ssdec.blif.  To do this, we run the command:

`yosys -p "read_blif ssdec.blif; read_verilog top.v; synth_ice40 -top top; write_verilog struct_top.v"`

ssdec.blif was generated using yosys by performing the following on ssdec.v:

`yosys -p "read_verilog ssdec.v; synth_ice40 -blif ssdec.blif"`

## Expected behavior

In struct_top.v, I expect to see some form of the mux logic I implemented in ssdec.v with its output connected to ss0.

## Actual behavior

In the resulting [struct_top.v](https://github.com/YosysHQ/yosys/files/4232786/struct_top.zip), there is no port connection to ss0, which was connected as an output to the ssdec module in the top module, but in the struct_top.v file, ss0 is not assigned to any port.

My yosys version is 0.9+932 (git sha1 3c6a566d, gcc 6.3.0-18+deb9u1 -fPIC -Os).

**Comment by eddiehung** [comment]
The BLIF is a bit-blasted format, and has no concept of busses. Thus `write_blif` will write out each bit in a bus as its own port (after uncommenting out the contents of `ssdec.v`):
```
.model ssdec
.inputs in[0] in[1] in[2] in[3] enable
.outputs out[0] out[1] out[2] out[3] out[4] out[5] out[6] out[7]
```

And when read in again via `./yosys -p "read_blif ssdec.blif; write_verilog"` you get:
```
module ssdec(\in[0] , \in[1] , \in[2] , \in[3] , enable, \out[0] , \out[1] , \out[2] , \out[3] , \out[4] , \out[5] , \out[6] , \out[7] );
```

And when you instantiate a cell using positional arguments in `top.v` here:
```
ssdec s1 (pb[3:0], 1'b1, ss0);
```
you are actually binding them to `\in[0]`, `\in[1]`, and `\in[2]`.

An (imperfect) workaround for this is to use the `read_blif -wideports` option which attempts to recover buses by their names. With this it looks to work:

```
$ yosys -p "read_blif -wideports ssdec.blif; read_verilog top.v; synth_ice40 -top top; write_verilog struct_top.v" 

<<SNIP>>

3.50. Printing statistics.

=== top ===

   Number of wires:                 42
   Number of wire bits:            141
   Number of public wires:          42
   Number of public wire bits:     141
   Number of memories:               0
   Number of memory bits:            0
   Number of processes:              0
   Number of cells:                 18
     SB_LUT4                        18

<<SNIP>>
```
