### ISSUE TITLE
Seems like non used modules in yosys screw up place and routing in nextpnr.

### ISSUE THREAD

**Issue by joseluisquiroga** [YosysHQ/yosys#1734]
I have created an small project to show the error.

https://github.com/messaging-cells/bug_synth_01

The expected behavior is to make OK when NS_SHOW_ERROR in 
https://github.com/messaging-cells/bug_synth_01/blob/master/rtl/test_bug_top.v
is set to 1.

To reproduce:
- clone the project.
- set NS_SHOW_ERROR to 1 in test_bug_top.v
- make

**Comment by daveshah1** [comment]
You aren't specifying a top module, and so an unused module is picked arbitrarily (if all modules are used then this will end up being the correct top module). Add `-top test_9_top` to `synth_ice40`.
