### ISSUE TITLE
Deprecate and then remove support for gcc-4.8

### ISSUE THREAD

**Issue by boqwxp** [YosysHQ/yosys#1772]
GCC 4.8 is a [very old](https://gcc.gnu.org/releases.html) compiler not used by [Ubuntu 16.04 LTS](https://packages.ubuntu.com/xenial/gcc) or [Debian 8](https://packages.debian.org/jessie/gcc).  [CentOS/RHEL 7](https://access.redhat.com/solutions/19458) seems to be the only currently-in-use distro that has gcc-4.8 as its default compiler.

However, there is an officially-recommended and supported [path](https://developers.redhat.com/blog/2019/03/05/yum-install-gcc-8-clang-6/) to installing a much more modern compiler that will work just fine for Yosys.

Additionally, nothing prevents users from using a more modern compiler built from source.  It's not that difficult, and users--sorry, users *who wish to compile Yosys*--who are on a severely outdated platform can IMO be expected to pay that small cost.

Support for gcc-4.8 does not come for free.  For example, see the code cruft added in #1766.  Or consider that 1/4 of the Travis CI resources are used making gcc-4.8 builds, presumably because it frequently breaks.  I think it's a good idea at least to deprecate gcc-4.8 support, warn on builds with gcc-4.8 that support will soon end, and then remove it entirely.

**Comment by KrystalDelusion** [comment]
Done with #3620
