### ISSUE TITLE
ghdlsynth build breaks

### ISSUE THREAD

**Issue by donnie-j** [YosysHQ/yosys#1856]
ghdlsynth uses the following to compile its interface module:
```
yosys-config --exec --cxx -c --cxxflags -o $@ $<
```

A recent change to yosys breaks the inclusion of rtlil.h... at line 380 it tries to include "constids.inc" which appears only in the kernel directory, and is not in the include path.  A quick hack to put the yosys/kernel directory in the path manually results in a working ghdl module.

I had a quick look at the changesets and it's not immediately obvious which change causes this, or if the build break is caused by an incomplete build or install issue, but it is in the last 2 days.  I have been tracking both ghdlsynth and yosys development, and this is a new bug.

Cheers, and thanks to all the Yosys developers.  In conjunction with the GHDL developer's work, very much progress has been made in just the last few weeks.

**Comment by eddiehung** [comment]
Sorry, I believe this is my doing for #1767! Please try #1858.

**Comment by eddiehung** [comment]
@donnie-j Can you confirm if this fixes your issue please?

**Comment by Xiretza** [comment]
Not OP, but 2d0b4033 still doesn't work - the error doesn't occur during compilation of yosys, but when ghdl-yosys-plugin includes the yosys headers:

```
In file included from /usr/share/yosys/include/kernel/yosys.h:277,
                 from src/ghdl.cc:19:
/usr/share/yosys/include/kernel/rtlil.h:380:10: fatal error: constids.inc: No such file or directory
  380 | #include "constids.inc"
      |          ^~~~~~~~~~~~~~
```

I think the occurences in both [`rtlil.cc`](https://github.com/YosysHQ/yosys/blob/5d18fdadfe758fed14a93977d3e8e83096c26c5a/kernel/rtlil.cc#L45) and [`yosys.cc`](https://github.com/YosysHQ/yosys/blob/5d18fdadfe758fed14a93977d3e8e83096c26c5a/kernel/yosys.cc#L519) are fine, only [`rtlil.h`](https://github.com/YosysHQ/yosys/blob/5d18fdadfe758fed14a93977d3e8e83096c26c5a/kernel/rtlil.h#L380) needs to be changed.

**Comment by Xiretza** [comment]
It'll also need an `$(eval $(call add_include_file,kernel/constids.inc))` in the Makefile to copy the file over during installation.

**Comment by eddiehung** [comment]
Thanks @Xiretza! Seems like I got the wrong end of the stick entirely. I still think there's value in #1858 as I believe convention is to include `<subdir>/<file>` regardless.

**Comment by donnie-j** [comment]
Yup, now seems to be fixed.  Thanks all.
