### ISSUE TITLE
Yosys aborts on $memrd/wr cells when saving json, reloading json, and continuing the same process 

### ISSUE THREAD

**Issue by tomverbeure** [YosysHQ/yosys#1908]
## Steps to reproduce the issue

Start Yosys and do this:
```
read_verilog CpuComplex.v
read_verilog -lib -D_ABC +/ice40/cells_sim.v
hierarchy -check -top CpuComplex   
proc
write_json CpuComplex.proc.json
exit
```

Restart Yosys and do this:
```
read_json CpuComplex.proc.json
flatten
```

Full repro environment can be found here: https://github.com/tomverbeure/yosys_error/tree/save_reload_crash.

Just clone and execute  `./run.sh`.

## Expected behavior

I expected to be able to use JSON to save and restore state and pick up where I left off.

[According](https://old.reddit.com/r/yosys/comments/fzrdje/yosys_aborts_when_saving_during_an_intermediate/fn5umzf/) to @daveshah1, the JSON netlist format shouldn't be used for that.

But at least, Yosys should bail with some error instead of just aborting.

## Actual behavior

Yosys aborts as follows:

```
...
Importing module CCPipelinedMemoryBusRam from JSON tree.
Importing module CCMasterArbiter from JSON tree.

2. Executing FLATTEN pass (flatten design).
Using template VexRiscv for cells of type VexRiscv.
<suppressed ~1 debug messages>
ERROR: Assert `memory_renames.count(memid) != 0' failed in passes/techmap/techmap.cc:425.
```

The abort is caused by the presence of `$memrd` and `$memwr` cells in the netlist. When I remove those, Yosys proceeds as expected.

## Work around

Use `write_ilang`/`read_ilang` instead of  `write_json`/`read_json`. That works fine.

The reason I wanted to use json is because it doesn't require a custom parser for most languages.

**Comment by nakengelhardt** [comment]
Proposed "fix": `write_json` should emit an error if it encounters `$memrd/$memwr`.

**Comment by Kmanfi** [comment]
> Proposed "fix": `write_json` should emit an error if it encounters `$memrd/$memwr`.

I am using "$memrd/$memwr" cells written in JSON. This proposed "fix" would break it.

**Comment by whitequark** [comment]
> I am using "$memrd/$memwr" cells written in JSON. This proposed "fix" would break it.

Without being able to associate them with memories (which are not representable in the current JSON format) there is not much that can be done with those cells. How are you using them?

**Comment by Kmanfi** [comment]
Using them in a custom "cxx" like backend as ports to read and write C array content.

**Comment by whitequark** [comment]
Are you inferring the memory width from the `\WIDTH` parameter of `$memrd` cells, and the memory depth from the `\ABITS` parameter?

**Comment by Kmanfi** [comment]
> Are you inferring the memory width from the `\WIDTH` parameter of `$memrd` cells, and the memory depth from the `\ABITS` parameter?

Yes.
I have added "torder" into write_json. Then those memrd and memwr cells are leveled in correct level of logic. $mem can't be used coz it's not possible to "torder" it.

**Comment by whitequark** [comment]
It seems like you are already using a patched version of Yosys to do what you want. This means that you won't be affected by the change as you can revert it in your own fork; however, I would personally argue that the JSON format can be extended to include expanded memories. The added complexity is minor, and they are still useful even without support for processes.

That said I would leave the final decision to @cliffordwolf.

**Comment by Kmanfi** [comment]
+1 to read expanded memories in with read_json.
