### ISSUE TITLE
Assert `wire' failed in passes/techmap/abc9_ops.cc:967 with &fraig in abc9.script

### ISSUE THREAD

**Issue by ZirconiumX** [YosysHQ/yosys#1914]
## Steps to reproduce the issue

Using [bug.tar.gz](https://github.com/YosysHQ/yosys/files/4471029/bug.tar.gz) run `yosys -s script.ys chess.v`. (Sorry, but `bugpoint` crashed while working on this, so I don't have anything more minimal than the input source)

## Expected behavior

ABC9 either succeeds or fails gracefully.

## Actual behavior

```
2.49.9.7. Executing ABC9_OPS pass (helper functions for ABC9).
ABC RESULTS:              $lut cells:     1636
ERROR: Assert `wire' failed in passes/techmap/abc9_ops.cc:968.
```

This is a tricky one; for example, replacing `synth_xilinx` with `synth_ecp5` works, but `synth_ice40` does not. The bug seems to be specifically related to `&fraig`; without it this is just the default ABC9 script. It's a shame, too; it seems to provide a pretty major reduction in delay, though at an expense of area (perhaps that could be fixed with a `abc9.script.flow3`-like approach?)

cc @eddiehung

**Comment by ZirconiumX** [comment]
(I forgot to attach the source files before hitting submit; they're attached now)

**Comment by eddiehung** [comment]
`&fraig` is not supported in any box-aware flow.

**Comment by ZirconiumX** [comment]
Right, okay; the ABC docs are not all that clear on this. Feel free to close this then.
