### ISSUE TITLE
memory_bram should have a "RAM initialises to zero" parameter

### ISSUE THREAD

**Issue by Ravenslofty** [YosysHQ/yosys#1958]
At present, `memory_bram` only supports "can't be initialised" and "initialises to anything", but (at least until `memory_bram` passes file information) Intel RAM initialises to zero, Xilinx UltraScale+ UltraRAM also does, and so does iCE40UP SPRAM.

It's fairly common for memory to default initialise to zero (I believe this is what nMigen does), and since the alternative is falling back to flops, it's better to utilise zero-initialised RAM where possible.

**Comment by smunaut** [comment]
jfyi I don't think the iCE40UP SPRAM inits to zero.
