### ISSUE TITLE
ld: library not found for -ltcl8.64)   

### ISSUE THREAD

**Issue by xinanhuang** [YosysHQ/yosys#2103]
Error generated when building yosys on mac os 10.14.6. 
Error occurred when building yosys-filterlib9774.

**Comment by lethalbit** [comment]
This was an issue in the past, make sure on macOS that you run the [Brewfile](https://github.com/YosysHQ/yosys/blob/master/Brewfile) to ensure that you have all of the needed dependencies on your system.
