### ISSUE TITLE
cxxrtl backend uses unsigned shift for signed shift cell

### ISSUE THREAD

**Issue by programmerjake** [YosysHQ/yosys#2111]
As far as I can tell, this should use `value::sshr` or set the `Signed` template parameter to true.

https://github.com/YosysHQ/yosys/blob/352731df4e0bf344cd20533a5561bc8ba3e07853/backends/cxxrtl/cxxrtl.h#L922-L925

**Comment by whitequark** [comment]
@programmerjake #2113 looks good?
