### ISSUE TITLE
ECP5 PDPW16KD primitive missing address lines?

### ISSUE THREAD

**Issue by madscientist159** [YosysHQ/yosys#2143]
Looking at the definition of the ECP5 PDPW16KD primitive in ```echlibs/ecp5/cells_bb.v```, the write port seems to be missing the upper 5 address lines when compared to the primitive in TN1264.  This is expected to make operation in any width less than 36 bits impossible.

Was this intentional?

**Comment by madscientist159** [comment]
@daveshah1 In the TN1264 document page Table 9 shows the extra address bits.

**Comment by daveshah1** [comment]
This looks to be an error in the docs, the PDPW16KD primitive in Diamond only has 9 address bits. Once again, if you can show a design that uses a write width other than 36 for PDPW16KD then I'll be happy to fix.

**Comment by madscientist159** [comment]
@daveshah1 I'll take your word for it -- it doesn't make much difference for our designs, and it wouldn't be the first time significant errors have been found in the Lattice documentation...
