### ISSUE TITLE
cxxrtl: signed shr doesn't sign-extend correctly for values smaller than chunk size

### ISSUE THREAD

**Issue by miek** [YosysHQ/yosys#2157]
When (signed) shr handles the final chunk
https://github.com/YosysHQ/yosys/blob/74e93e083ff23f3381fe2409e5847f9843840b17/backends/cxxrtl/cxxrtl.h#L382

if, for example, chunk::bits is 32, Bits is 16, and the shift is 1 then this will only fill bit 31 of the chunk.
The RHS should be equivalent to `chunk::mask << (Bits - shift_bits)` when the value is smaller than the chunk size.

Also I think there's an off-by-one, it should assign to `result.data[chunks - shift_chunks - 1]`.

**Comment by whitequark** [comment]
Yep, that line is a bug--I actually noticed it this morning. Care to send a PR?

**Comment by miek** [comment]
Yep, will do. I need to think about it some more now though, I just realised this applies to larger values too. I think it hits any value that's not a multiple of the chunk size, when the shift is less than the chunk size.
