### ISSUE TITLE
Enable building yosys and yosys-abc under Android

### ISSUE THREAD

**Issue by mohamed** [YosysHQ/yosys#2324]
- `yosys` is failing to link under Android due to missing `-latomic`. #2323 fixes that by always linking to `libatomic`
- `yosys-abc` fails to compile under Android due to undefined `S_IWRITE` and `S_IREAD` macros. These are legacy macros and are deprecated in favor of `S_IRUSR` and `S_IWUSR`. https://github.com/YosysHQ/abc/pull/7 fixes this by defining the deprecated macros in terms of the new ones iff the old are undefined while the new are defined.

**Comment by mohamed** [comment]
#2323 is not needed. The issue can be resolved by building with `LDLIBS=-latomic make`

**Comment by whitequark** [comment]
Both of the PRs referenced are resolved, closing.
