### ISSUE TITLE
Is there a way to specify internal pullups for the ICE40 family?

### ISSUE THREAD

**Issue by TACIXAT** [YosysHQ/yosys#2354]
Sorry that this is not an issue with the project. I am working with the ICE40 HX-8k and am not sure how to specify that certain pins should use the internal pull-up resistors. Any advice would be greatly appreciated. Using yosys and nextpnr.

**Comment by Ravenslofty** [comment]
[Yes.](https://github.com/YosysHQ/nextpnr/blob/master/docs/ice40.md)
