### ISSUE TITLE
Would it be at all useful to document the RTLIL text format?

### ISSUE THREAD

**Issue by RobertBaruch** [YosysHQ/yosys#2445]
I found myself idly doing this, and then wondered if I was wasting my time? Would this be a useful addition to the manual?

![rtlil](https://user-images.githubusercontent.com/1783950/99909399-25c3ab00-2c9d-11eb-968c-05b5cba64a90.JPG)

**Comment by whitequark** [comment]
Sure, seems reasonable. The text fromat is already stable to an extent due to nMigen relying on it.
