### ISSUE TITLE
Extract FSM Does Not Work

### ISSUE THREAD

**Issue by myzinsky** [YosysHQ/yosys#2532]
Following the example here:

https://stackoverflow.com/questions/32645965/fsm-export-using-yosys/65638821#65638821

``` bash
yosys -p 'read_verilog fsm.v; proc; opt; fsm -nomap; fsm_export -o test.kiss2'
```

does not export any kiss2 file :-(

Is that a bug? Or has the usage changed?

**Comment by Ravenslofty** [comment]
This could be #2402; if there are no FSMs detected, then `fsm_export` does nothing.
