### ISSUE TITLE
XAIGER assert

### ISSUE THREAD

**Issue by madscientist159** [YosysHQ/yosys#2650]
After upgrading Yosys to the latest GIT master (26e01a) I'm now seeing an XAIGER assert when trying to build Kestrel [1] for the Lattice ECP5:

```
13.45.23.1. Executing ABC9_OPS pass (helper functions for ABC9).

13.45.23.2. Executing ABC9_OPS pass (helper functions for ABC9).

13.45.23.3. Executing XAIGER backend.
ERROR: Assert `!aig_map.count(bit)' failed in backends/aiger/xaiger.cc:435.
```

This was not an issue on the earlier GIT version in use (Jan/Feb. 2021).

[1] https://gitlab.raptorengineering.com/kestrel-collaboration/kestrel-litex/litex-boards/-/blob/master/README.md

**Comment by Ravenslofty** [comment]
Do you have a logic loop in your code? That assert means XAIGER attempted to add a wire multiple times, which happens when there are logic loops.

Also, does SCC point out any loops?

**Comment by eddiehung** [comment]
Closing this for now as there's not enough information to reproduce this issue. Please attach all Yosys input files if you wish to reopen.
