### ISSUE TITLE
Processes in whitebox causes synth_ecp5 JSON backend to fail

### ISSUE THREAD

**Issue by gatecat** [YosysHQ/yosys#2667]
Run:

```
yosys -p "add -mod top; synth_ecp5 -json /dev/null"
```

as the ECP5 distributed RAM whiteboxes contain processes but nothing elaborates those processes; the JSON backend is now failing:

```
ERROR: Module DPR16X4C contains processes, which are not supported by JSON backend.
```

A workaround would be to unwhitebox those cells as I don't think there is much useful optimisation that can be done anyway, but I suspect this issue may well affect other situations involving boxes in processes as well.

cc @edbordin

**Comment by mwkmwkmwk** [comment]
Would running `blackbox` command on all whitebox modules at the end of the synthesis flow solve this problem?

**Comment by gatecat** [comment]
Yes, that seems like a better way to deal with this
