### ISSUE TITLE
 Does the operation of YOSYS depend on the hardware features of the computer?

### ISSUE THREAD

**Issue by demirmehmet0** [YosysHQ/yosys#2692]
I want to synthesize XOR gates with YOSYS, but I get different results every time I try. the tool I'm using is 'abc -g XOR'. Do the results I get from this tool change with the features of the computer such as processor, video card, RAM?

**Comment by Ravenslofty** [comment]
We know that different compilers and different operating systems can produce different results, along with big-endian processor architectures outright being broken at the moment. But other than that, no: Yosys is (hopefully) deterministic, and the things you listed should not have any effect on the result.
