### ISSUE TITLE
integer and genvar declared in for initialization

### ISSUE THREAD

**Issue by mehdimolum** [YosysHQ/yosys#2693]
Hi,

I have numerous systemverilog codes with `integer` and `genvar` inside paranthesis (in the same line as `for`); e.g.,  `for (integer i = 0; i<10; i++)` but I get an error at `read_verilog`. Nevertheles if I define `integer i` before `for`, I don't have any problem. 

I am wondering if it would be possible to support this? any advise is appreciated

**Comment by zachjs** [comment]
#2248 implements the behavior you are looking for. While that PR is not yet ready to be merged, you may be interested in trying it out.

**Comment by mehdimolum** [comment]
@zachjs thanks! it did the job

**Comment by zachjs** [comment]
These features have been implemented via #2986 and #2987.
