### ISSUE TITLE
Yosys and OCU35 or other CMOS synthesis and placement/routed examples

### ISSUE THREAD

**Issue by PPlinux** [YosysHQ/yosys#2720]
Dear,

can onyone point me to synthesis generated for OCU35 or other CMOS technologies (e.g. OpenPDK45) 
and required configuration (how-to) ? 
Maybe there are also placement/routed examples available ?

Greetings,

Patrick Pelgrims

**Comment by gatecat** [comment]
There is an example synthesis script for OSU035 here: https://github.com/YosysHQ/yosys/tree/master/examples/osu035
