### ISSUE TITLE
frontends/verific/verific.cc:46:11: fatal error: vhdl_file.h

### ISSUE THREAD

**Issue by chagainota** [YosysHQ/yosys#2732]
Hi

I get the following error when trying to compile Yosys with ENBALE_VERIFC = 1
frontends/verific/verific.cc:46:11: fatal error: vhdl_file.h: No such file or directory
  #include "vhdl_file.h"
           ^~~~~~~~~~~~~
compilation terminated.
Makefile:709: recipe for target 'frontends/verific/verific.o' failed
make: *** [frontends/verific/verific.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by mwkmwkmwk** [comment]
The Verific support will only work with YosysHQ version of Verific.  If you have a YosysHQ support contract, please contact us via support channels.  Combining yosys with any other version of Verific is unsupported and will result in multiple known issues.
