### ISSUE TITLE
bad/no optimization on simple MUX&XOR design

### ISSUE THREAD

**Issue by Riesi** [YosysHQ/yosys#2750]
Hello,
So I am attending a lab at the TU Wien where we have to fix the Trusthub trojans and we are currently relying on the subpar optimization of the code via Yosys to prevent an otherwise not connected signal from getting optimized away. 
In short we trick the optimizer to think a signal is used, when it isn't to prevent the trojan from getting optimized away.
Design used (also attached as a file):
```
module mask_gate(
    input trojan,
    input legit,
    output masked
    );

assign masked = trojan^legit?~trojan:legit;

endmodule
```
 I also tried to replace the MUX and XOR with basic components like AND/OR to maybe get it optimized that way, but that didn't help. Hopefully the commands used are all that is needed to trigger decent optimization. (maybe I am missing some cool command :sweat_smile: )

I am not sure, if this is a duplicate of #324. 

Thanks in advance!

```
$ yosys --version
Yosys 0.9+4052 (git sha1 445208086, gcc 10.2.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os)
```

## Steps to reproduce the issue

```
read_verilog mask_gate.v
prep -auto-top
opt -full
show
```
and 
```
read_verilog mask_gate_basic.v
prep -auto-top
opt -full
show
```
Here is a zip with the masking gate designs:
[mask_gates.zip](https://github.com/YosysHQ/yosys/files/6460415/mask_gates.zip)

## Expected behavior
The whole design should be optimized away and `legit` should be directly mapped to `masked`.

Vivado is able to optimize both designs and shows `trojan` being disconnected.
Vivado mask_gate.v:
![2021-05-11-17-36-05](https://user-images.githubusercontent.com/27691485/117848008-2a980d80-b283-11eb-8792-01a0f938e387.png)

## Actual behavior
The design isn't optimized at all and this results in `trojan` still being connected even though it doesn't influence `masked`.
Yosys:
![2021-05-11-17-48-09](https://user-images.githubusercontent.com/27691485/117848124-456a8200-b283-11eb-80cf-be41f5421e68.png)

**Comment by mwkmwkmwk** [comment]
Yes, currently `opt` only does relatively simple optimizations, with no heavyweight logic rewriting.  However, in a normal synthesis flow, this design is simplified into nothingness by `abc` later, so it's not much of an issue in practice.

**Comment by mwkmwkmwk** [comment]
Adding heavyweight logic rewriting into yosys itself would be a pretty major undertaking (and would involve lots of discussion of where to fit it in the flow and why), so unless you have some good rationale to want it in the coarse phase (or before abc for other reasons), I'd say we should close this issue
