### ISSUE TITLE
cxxrtl - debug_item could use get<> and set<>

### ISSUE THREAD

**Issue by galibert** [YosysHQ/yosys#2877]
debug_item C++ interface is currently minimal.  Support for get<> and set<> as values have would be rather nice and would at the same time avoid people messing up between curr and next.

Perhaps it should have the same interface as value<>, but value has a big interface which may not be that useful for external code piloting the simulation.

**Comment by whitequark** [comment]
The interface will look like this:
```cxx
// toggle clock
bool clk = debug["clk"].get<1, bool>();
debug["clk"].set<1>(!clk);
```

You will have to provide the expected width of the value/wire referenced by the debug item, and it is checked (using an assert, in debug builds) against the actual width stored in the debug item.

**Comment by whitequark** [comment]
See #2880.
