### ISSUE TITLE
Running synth_xilinx with abc9 multiple times causes an error

### ISSUE THREAD

**Issue by acomodi** [YosysHQ/yosys#2972]
## Steps to reproduce the issue

1. Build yosys - `Yosys 0.9+4276 (git sha1 75a4cdfc8, clang 6.0.0-1ubuntu2 -fPIC -Os)`
1. Extract the [tar.gz](https://github.com/YosysHQ/yosys/files/7019796/abc-fail.tar.gz) archive
1. `cd abc-fail && make`

## Expected behavior

The flow should complete without errors.

## Actual behavior

Running `synth_xilinx -abc9` when there are FDPE (or other FF) cells causes the following error:

```
3.44. Executing ABC9 pass.

3.44.1. Executing ABC9_OPS pass (helper functions for ABC9).

3.44.2. Executing ABC9_OPS pass (helper functions for ABC9).

3.44.3. Executing SCC pass (detecting logic loops).
Found 0 SCCs in module top.
Found 0 SCCs.

3.44.4. Executing ABC9_OPS pass (helper functions for ABC9).
ERROR: Attempted to add new module named '\FDPE_$abc9_byp', but a module by that name already exists
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

```

**Comment by eddiehung** [comment]
Attached test case appears to be corrupted.

**Comment by eddiehung** [comment]
Please give #2993 a try.

**Comment by acomodi** [comment]
@eddiehung Thanks, I have tested #2993 and the test passes now.
