### ISSUE TITLE
Update PPA to v0.10

### ISSUE THREAD

**Issue by mcandre** [YosysHQ/yosys#3018]
Hi,

I am a new embedded systems programmer curious about getting into FPGA's. I see that there is an Ubuntu PPA repository available with precompiled binaries for yosys. Could this be updated to reflect recent releases?

https://launchpad.net/~saltmakrell/+archive/ubuntu/ppa

**Comment by mmicko** [comment]
For this you would need to contact PPA repository maintainer(s) directly, since we are not maintaining these releases.
