### ISSUE TITLE
Respect TMPDIR environment variable when creating temporary files

### ISSUE THREAD

**Issue by b1f6c1c4** [YosysHQ/yosys#3023]
## Steps to reproduce the issue

I'm using Linux with tmpfs located somewhere other than `/tmp`. In https://github.com/YosysHQ/yosys/blob/master/kernel/yosys.cc#L379-L460, I noticed that the actual value of `TMPDIR` is never read but is hard-coded to `/tmp`.

## Expected behavior

If I set `TMPDIR=/dev/shm`, Yosys should put temporary files into `/dev/shm` when calling ABC.

## Actual behavior

If I set `TMPDIR=/dev/shm`, Yosys still put temporary files into `/tmp` when calling ABC.

**Comment by lethalbit** [comment]
This bug looks to have been fixed as the line https://github.com/YosysHQ/yosys/blob/master/kernel/yosys.cc#L402 calls `std::getenv("TMPDIR");` to assign the temporary directory.
