### ISSUE TITLE
Signed value used for bit select gives unexpected behavior.

### ISSUE THREAD

**Issue by tcal-x** [YosysHQ/yosys#3051]
## Steps to reproduce the issue

`ex.v` source:
```
module top (
    input [1:0] i,
    output reg [3:0] result
);

   wire signed [3:0] idx = {2'b00,i};

   always @(*) begin
      result = 4'b0000;
      result[idx] = 1'b1;
   end

endmodule
```
At the Yosys prompt run the following commands:
```
read_verilog ex.v
synth
show
```
You will see this circuit, in which the high 3 bits of "result" are tied to zero:
![bad](https://user-images.githubusercontent.com/63030309/138034567-8a856d7a-854f-4917-886e-b1b8236b5026.png)

## Expected behavior

I expected the 2-bit "i" input to be decoded into one-hot representation in the 4-bit "result" output.

**If I remove the "signed" modifier from `idx` and use the same flow, then I get the decoder that I was expecting**:

![good](https://user-images.githubusercontent.com/63030309/138035099-6e3b67ec-466c-4e4a-9a23-9d1af6e8d7f5.png)

## Actual behavior

The high 3 bits of "result" are always zero (incorrectly).   The low bit of "result" is asserted only when "i" is 2'b00 (correctly).   Refer to the first diagram.

**Note:** With the original circuit where I think I'm seeing incorrect behavior, the output of `synth_xilinx` is even stranger than the `synth` output shown above.

Origin: https://github.com/SymbiFlow/symbiflow-arch-defs/issues/2307

**Comment by gergoerdi** [comment]
Even the bit width extension turns out to be a red herring, as the following code on its own already exhibits the problem:

```
module top (
    input [1:0] i,
    output reg [3:0] result
);

   wire signed [1:0] idx = i;

   always @(*) begin
      result = 4'b0000;
      result[idx] = 1'b1;
   end

endmodule
```
