### ISSUE TITLE
Flatten much slower compared to older yosys

### ISSUE THREAD

**Issue by mtuomi** [YosysHQ/yosys#3064]
## Steps to reproduce the issue

I'm working with big designs with millions of cells and the flatten command is very slow with current Yosys.
But I have stored older yosys binary which I use only for flattening. The difference can be hours vs seconds.
I wanted to try if I can make a simple case to demonstrate this. I don't know when it has gotten slower.

The attached python script will generate a simple design with big number of instantiated buffer modules (just wire inside) chained together.

bufCount variable in python script defines how many buffers are created.

Flattening time behaves roughly like this when number of buffers is increased :
20k 90sec
30k 272sec
40k 496sec
50k 743sec
60k 1040sec

For comparison, even the 60k buffers are flattened in about one second with old yosys.

[gen.py.zip](https://github.com/YosysHQ/yosys/files/7427877/gen.py.zip)

Run the attached gen.py python script, it will generate issue.il file
Then do : yosys -p 'read_ilang issue.il; flatten'

## Expected behavior

Yosys 0.6+     243 (git sha1 fa1c7cc, clang 7.3.0 -fPIC -Os)
Time spent: 81% 1x flatten (1 sec), 18% 2x read_ilang (0 sec)

## Actual behavior

Yosys 0.10+51 (git sha1 19c2d6e15, clang 13.0.0 -fPIC -Os)
Time spent: 99% 1x flatten (86 sec), 0% 2x read_ilang (0 sec)

**Comment by mtuomi** [comment]
@whitequark Hey, would you have any idea why the flatten is exponentially slower when more cells are flattened?

**Comment by whitequark** [comment]
I don't. Could you bisect the slowdown to a specific commit, please? The range from 0.6 to 0.10 is very long.

**Comment by mtuomi** [comment]
Ok I will narrow it down

**Comment by mtuomi** [comment]
@whitequark 
Yosys 0.9+2406 (git sha1 6ac54a74f, clang 13.0.0 -fPIC -Os)
Time spent: 81% 1x flatten (0 sec), 18% 2x read_ilang (0 sec), ...

Yosys 0.9+2406 (git sha1 5a5a9b4ff, clang 13.0.0 -fPIC -Os)
Time spent: 99% 1x flatten (45 sec), 0% 2x read_ilang (0 sec), ...

It happens between these versions. There is only one day in between.

**Comment by mtuomi** [comment]
@whitequark 
Even further narrowed it down, it is this commit that makes it slow 

Yosys 0.9+2406 (git sha1 d3e210030, clang 13.0.0 -fPIC -Os)
Time spent: 99% 1x flatten (45 sec), 0% 2x read_ilang (0 sec), ...

The previous one was still fast:
Yosys 0.9+2406 (git sha1 66255dab4, clang 13.0.0 -fPIC -Os)
Time spent: 77% 1x flatten (0 sec), 22% 2x read_ilang (0 sec), ...

**Comment by whitequark** [comment]
Ah. If you can revert that commit and send a PR, that would be great!

**Comment by mwkmwkmwk** [comment]
Actually let's not revert that commit, I should have a better solution soon...

**Comment by mtuomi** [comment]
Fix looks good! I tried with 1 Million cells to flatten and it runs in 11 seconds. Thank you for a fast fix!

**Comment by mwkmwkmwk** [comment]
Don't close the issue just yet, it'll be auto-closed when the fix actually lands in master.

**Comment by mtuomi** [comment]
Ok sorry, didn't know that.
