### ISSUE TITLE
abc: dont_use value is ignored

### ISSUE THREAD

**Issue by bfg86** [YosysHQ/yosys#3065]
## Steps to reproduce the issue
unzip [testcase.zip](https://github.com/YosysHQ/yosys/files/7441170/testcase.zip)
yosys -s syn.ys

## Expected behavior
I added dont_use : "false"; to the NAND gate in cmos_cells.lib. 
Expected ABC to not report any dont_use cells, and netlist to contain 1 NAND + 1 NOT.

## Actual behavior
In ABC log it says:
```ABC: Library "demo" from "/home/test/tmp/cmos_cells.lib" has 3 cells (2 skipped: 2 seq; 0 tri-state; 0 no func; 1 dont_use).  Time =     0.00 sec```
and the module is implemented with 1 NOR cell and 2 NOT cells.

**Comment by Ravenslofty** [comment]
ABC bugs should be filed against ABC itself, not Yosys.

**Comment by bfg86** [comment]
Right, created an issue at berkeley-abc/abc. Closing this one.
