### ISSUE TITLE
Where to start to create custom technology library

### ISSUE THREAD

**Issue by eemincetin** [YosysHQ/yosys#3144]
Hi there, I am trying to create custom technology library. Let's say I have a design which has a FIFO as a subcircuit. I want synthesizer to map this subcircuit (FIFO) to the FIFO Blackbox and other stuff to the where they are belong. How can I create a custom technology library?

**Comment by Ravenslofty** [comment]
Is your aim here to get Yosys to infer the FIFO subcircuit as a FIFO and then instantiate your FIFO blackbox? Because that's a *really hard problem* and Yosys can't do that.

If you just want to transform a specific module into some other module then there's the `techmap` pass for that.
