### ISSUE TITLE
Mux optimisation

### ISSUE THREAD

**Issue by Kmanfi** [YosysHQ/yosys#324]
Is there any command or combination of commands that optimizes following?
I know this kind of optimisation might brake mux-trees but when used as very last optimisation pass it might reduce cell count of design.

Lowest bit of $mux output Y can be driven by input s because of constants in case.
Then highest bit can be just $and with s and f.
```
read_verilog mux_selector.v
hierarchy -top lowest_bit_is_selector

proc
pmuxtree
opt -mux_bool
clean -purge
stat
dump
shell
```

```
module lowest_bit_is_selector (s, f, z);
input s, f;
output [1:0] z;

	always @* begin
		case (s)
			1'b1: z = {f, 1'b1};
			1'b0: z = {1'b0, 1'b0};
		endcase
	end
endmodule
```

```
  cell $mux $auto$pmuxtree.cc:65:recursive_mux_generator$5
    parameter \WIDTH 2
    connect \A { \f 1'0 }
    connect \B 2'01
    connect \S \s
    connect \Y \z
  end

```

**Comment by mwkmwkmwk** [comment]
This mux cannot currently be optimized at the coarse level, but will be properly optimized in the fine phase of the synthesis: just try `techmap; opt` instead of `opt -mux_bool`
