### ISSUE TITLE
Blinky from apicula does not get optimized completely

### ISSUE THREAD

**Issue by catkira** [YosysHQ/yosys#3266]
## Steps to reproduce the issue

load this file in yosys with
read_verilog -DLEDS_NR=3 blinky.v

https://github.com/YosysHQ/apicula/blob/master/examples/blinky.v

## Expected behavior
I would expect that the 26 bit wide ctr_d wire and dff get reduced to 3 bit wide. 

## Actual behavior
The wire and register stay 26 bit wide, even after I execute opt_dff
<img width="796" alt="dff" src="https://user-images.githubusercontent.com/13425558/161601920-8f4096b6-e095-4a65-b93a-0e00bab68105.png">

**Comment by mwkmwkmwk** [comment]
how? removing lower bits of the counter is obviously impossible here

**Comment by catkira** [comment]
Ah yes, I did not read the code correctly ^^

**Comment by tcal-x** [comment]
I'm confused by the `<3>` at the _input_ to the `ctr_q` rhombus.    Is that a known quirk?

**Comment by catkira** [comment]
yes, that also confused me, if only 3 bits come out of the FF, some input bits should be unused. But they are used, because the counter counts up from 0 to max_value.
