### ISSUE TITLE
PROC_ARST can not identify the async reset

### ISSUE THREAD

**Issue by ZachGu** [YosysHQ/yosys#3304]
## Steps to reproduce the issue

Create a file called `test.v` with the following contents:
```
module top (clk, rst_n, in, sel, out);
input clk, rst_n, sel, in;
output out;

reg test[0:1];

always @(posedge clk or negedge rst_n) begin
  if (!rst_n)
    test[sel] <= 0;
  else
    test[sel] <= in;
end

assign out = test[0] & test[1];

endmodule
```
Then run `yosys -p 'read_verilog test.v; proc;'.`

( Yosys 0.17+0 (git sha1 d562bfd16, gcc 9.3.0-17ubuntu1~20.04 -fPIC -Os))

## Expected behavior

Complete with no issues.

## Actual behavior

The following error printed:
```
2.5. Executing PROC_ARST pass (detect async resets in processes).
Found async reset \rst_n in `\top.$proc$test.v:7$3'.
ERROR: Async reset \rst_n yields non-constant value 1'm for signal \test[0].
```

**Comment by mwkmwkmwk** [comment]
This is not a bug — this code assigns to a dynamically-selected bit in the "reset" branch of the if, and thus doesn't actually describe an async reset circuit.

**Comment by ZachGu** [comment]
> This is not a bug — this code assigns to a dynamically-selected bit in the "reset" branch of the if, and thus doesn't actually describe an async reset circuit.

I have tried this code with Design Compiler and there is no errors reported.
