### ISSUE TITLE
Failed to evaluate signal

### ISSUE THREAD

**Issue by 1353369570** [YosysHQ/yosys#3309]
## Steps to reproduce the issue
Consider the following piece of code:
module top  ( var_ad, var_ab, var_ac ); 
  input var_ad ; 
  input var_ab ; 
  output var_ac ; 
 always @ ( posedge var_ad ) 
 if ( var_ab ) begin 
 var_ac  <= 1'b0; 
 end else if ( var_ad ) begin 
 var_ac  <=! var_ad  ; 
 end 
 endmodule 
Run with yosys version

Generated by Yosys 0.9+4081,Yosys 0.15 (git sha1 UNKNOWN, clang 10.0.0-4ubuntu1 -fPIC -Os)

and the following command

$ yosys -p 'read_verilog rtl.v; proc;opt -full;eval  -set var_ad 1 -set var_ab 1'
[...]
Failed to evaluate signal \var_ac: Missing value for \var_ac.

**Comment by nakengelhardt** [comment]
`eval` only works for combinatorial circuits. `var_ac` is a register output.

**Comment by 1353369570** [comment]
这是来自QQ邮箱的假期自动回复邮件。收到。                  祝好！                  张漪

**Comment by nakengelhardt** [comment]
...please exclude github notifications from your autoresponder.
