### ISSUE TITLE
Equivalence checking issue

### ISSUE THREAD

**Issue by alaindargelas** [YosysHQ/yosys#3428]
## Steps to reproduce the issue

While trying to prove https://github.com/antmicro/yosys-uhdm-plugin-integration/pull/925, and facing an unproven gate to gate situation with the following testcase:

https://github.com/YosysHQ/yosys/blob/master/tests/simple/fsm.v

compiled to gate level by the following script:

read_verilog -sv fsm.v 
synth_xilinx
write_verilog fsm_gate.v

Then trying to prove it's equivalence against itself (strict copy), cannot be proven by the following script (No matter how big the sequential depth is set):

read_verilog fsm_gate.v ...../share/yosys/xilinx/cells_sim.v ..../share/yosys/xilinx/cells_xtra.v
prep -flatten -top fsm_test
splitnets -ports;;
design -stash surelog
read_verilog fsm_gate.v ...../share/yosys/xilinx/cells_sim.v ..../share/yosys/xilinx/cells_xtra.v
splitnets -ports;;
prep -flatten -top fsm_test
design -stash yosys
design -copy-from surelog -as surelog fsm_test
design -copy-from yosys -as yosys fsm_test
equiv_make surelog yosys equiv
prep -flatten -top equiv
opt_clean -purge
opt -full
equiv_simple -seq 5
equiv_induct -seq 5
equiv_status -assert

Of course the original problem faced was trying to compare 2 netlists coming from 2 parsers. But faced with the unproven situation, I tried with the strict same netlist, and that also failed.

**Comment by nakengelhardt** [comment]
Related to #2728, we are still working on it.
