### ISSUE TITLE
High memory usage during parallel build

### ISSUE THREAD

**Issue by matsievskiysv** [YosysHQ/yosys#3430]
`yosys` takes more than 30Gb of RAM when it's being built in parallel (`make -j` option)

## Steps to reproduce the issue

```bash
git clone https://github.com/YosysHQ/yosys
pushd yosys
make PREFIX=/opt/yosys config-gcc
make PREFIX=/opt/yosys -j
```

## Expected behavior

`yosys` to require approximately the same amount of RAM for parallel build as for the regular one.

## Actual behavior

Something eats up memory during parallel build.

**Comment by jix** [comment]
This is expected `make -j` behavior and not Yosys specific. Instead use `make -j N` where N is replaced by the number of available cores or `make -j $(nproc)` if you have `nproc` installed. From the `make` man-page "If the -j option is given without an argument, make will not limit the number of jobs that can run simultaneously."
