### ISSUE TITLE
Failed to use a separate (out-of-tree) build directory

### ISSUE THREAD

**Issue by LvmhZhD** [YosysHQ/yosys#3501]
### Version

0.22+1 (git sha1 c4a52b1b0, gcc 11.2.0-19ubuntu1 -fPIC -Os)

### Reproduction Steps

when i  run 
`mkdir build ; cd build`
`make -f ../Makefile`

### Expected Behavior

make without errors

### Actual Behavior

`zhaodonglv@lvzhd:~/yosys/build$ make -f ../Makefile -j`
`fatal: '../' does not appear to be a git repository`
`fatal: Could not read from remote repository.`
`...`
` [ 89%] Building techlibs/xilinx/xilinx_dffopt.o`
`[ 99%] Building yosys-config`
`[ 99%] Building yosys-abc`
`cp: cannot stat 'abc/abc-ab5b16e': No such file or directory`
`make: *** [../Makefile:810: yosys-abc] Error 1`
`make: *** Waiting for unfinished jobs....`

**Comment by lethalbit** [comment]
Currently the build system only supports in-tree builds, this is a known limitation and work is being done when possible to support out-of-tree builds.
