### ISSUE TITLE
Different synthesis result by changing spaces to newlines

### ISSUE THREAD

**Issue by dwRchyngqxs** [YosysHQ/yosys#3735]
### Version

Yosys 0.28+4 (git sha1 7efc50367, clang 10.0.0-4ubuntu1 -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

Download the archive [files.tar.gz](https://github.com/YosysHQ/yosys/files/11288674/files.tar.gz), extract it in a new folder.
There are two design, depending on whether `synth_ecp5` is given the `-abc9` flag or not.
The bug without using `-abc9`:
```
sed 's/ /\n/' stdabc.v > stdabc.newlines.v
yosys -p "read_verilog stdabc.v; synth_ecp5; tee -o stdabc.json stat -json; write_verilog stdabc.synth.v
yosys -p "read_verilog stdabc.newlines.v; synth_ecp5; tee -o stdabc.newlines.json stat -json; write_verilog stdabc.newlines.synth.v
```
Both synthesised designs are different, the report shows different number of cells.
The bug with `-abc9`:
```
sed 's/ /\n/' abc9.v > abc9.newlines.v
yosys -p "read_verilog abc9.v; synth_ecp5 -abc9; tee -o abc9.json stat -json; write_verilog abc9.synth.v
yosys -p "read_verilog abc9.newlines.v; synth_ecp5 -abc9; tee -o abc9.newlines.json stat -json; write_verilog abc9.newlines.synth.v
```
Both synthesised designs are different, the report shows different number of cells.

### Expected Behavior

Synthesis results should be the same.

### Actual Behavior

Synthesis results differ.

**Comment by Ravenslofty** [comment]
#3713
