### ISSUE TITLE
Issue while running make test

### ISSUE THREAD

**Issue by Asma-Mohsin** [YosysHQ/yosys#3800]
### Version

Yosys 0.30+1 (git sha1 5813809ad, clang 10.0.0-4ubuntu1 -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

git clone https://github.com/YosysHQ/yosys
cd yosys
make -j$(nproc)
sudo make install
make test

### Expected Behavior

test passed

### Actual Behavior

make[1]: Leaving directory '/home/asma_mohsin/Desktop/FABulous/yosys/tests/sat'
cd tests/sim && bash run-test.sh
Generate FST for sim models
Test tb_adffe
FST info: dumpfile tb_adffe opened for output.
Test tb_adff
FST info: dumpfile tb_adff opened for output.
Test tb_adlatch
FST info: dumpfile tb_adlatch opened for output.
Test tb_aldffe
FST info: dumpfile tb_aldffe opened for output.
Test tb_aldff
FST info: dumpfile tb_aldff opened for output.
Test tb_dffe
FST info: dumpfile tb_dffe opened for output.
Test tb_dffsr
FST info: dumpfile tb_dffsr opened for output.
Test tb_dff
FST info: dumpfile tb_dff opened for output.
Test tb_dlatchsr
FST info: dumpfile tb_dlatchsr opened for output.
Test tb_dlatch
FST info: dumpfile tb_dlatch opened for output.
Test tb_sdffce
FST info: dumpfile tb_sdffce opened for output.
Test tb_sdffe
FST info: dumpfile tb_sdffe opened for output.
Test tb_sdff
FST info: dumpfile tb_sdff opened for output.
make[1]: Entering directory '/home/asma_mohsin/Desktop/FABulous/yosys/tests/sim'
ERROR: Error opening 'tb_adffe.fst' as FST file
make[1]: *** [run-test.mk:6: sim_adffe.ys] Error 1
make[1]: Leaving directory '/home/asma_mohsin/Desktop/FABulous/yosys/tests/sim'
make: *** [Makefile:858: test] Error 2

**Comment by mmicko** [comment]
As mentioned on Slack, old version of iverilog have been used. Updating solved the issue.
