### ISSUE TITLE
latexpdf docs build fails due to emoji character

### ISSUE THREAD

**Issue by DanielG** [YosysHQ/yosys#3905]
Hi,

I'm seeing the following fatal error when running `make docs DOC_TARGET=latexpdf`: 

```
! LaTeX Error: Unicode character 👇 (U+1F447)
               not set up for use with LaTeX.
```

Removing the entirely unnecessary emojis fixes it.

--Daniel

**Comment by DanielG** [comment]
@KrystalDelusion your #3783 seems to be at fault here.

**Comment by KrystalDelusion** [comment]
Thanks for catching that, I'm curious how Read The Docs gets around this since it seems to build the pdf fine (albeit without the emoji)

**Comment by Ravenslofty** [comment]
I somewhat disagree that the emoji (which through a [draft blog post](https://gist.github.com/Ravenslofty/0e757ae8262b671b23f2cfdbe81eec9a) I was writing got adopted by YosysHQ and eventually made a documentation entry) are "entirely unnecessary"; it's a reasonable if stylistic way of getting attention to the change in question (I adopted it from [fasterthanlime](https://fasterthanli.me/)).
