### ISSUE TITLE
Feature request: support DFFs with clock enable in shregmap

### ISSUE THREAD

**Issue by azonenberg** [YosysHQ/yosys#407]
The current shregmap pass cannot infer a shift register with clock enable (for example a Xilinx SRLC32E primitive).

It seems like the best way to handle this would be to infer generic DFFCE cells in an earlier pass, then shregmap, then map all remaining DFF/DFFCE cells to native library primitives.

**Comment by daveshah1** [comment]
shregmap now supports clock enables, and as of #914 is used by `synth_xilinx` to extract cells such as SRLC32E.
