### ISSUE TITLE
Yosys produces wrong cxxrtl model for some circuits (did I do something wrong?)

### ISSUE THREAD

**Issue by flaviens** [YosysHQ/yosys#4136]
### Version

Yosys 0.37+1 (git sha1 242ae4ef0, gcc 7.5.0-6ubuntu2 -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

Hi there!

Thank you very much with your so many contributions!
[On this simple example repo](https://github.com/flaviens/cxxrtl-b1) that I could reduce, Yosys fails at producing a correct CXXRTL model (cxxrtl.cpp gets produces but g++ complains).
I'm using `g++ (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0` on Ubuntu 22.04.
Is there anything that I am doing wrongly?

Thank you!
Flavien

### Expected Behavior

Successful compilation

### Actual Behavior

Compilation fails

**Comment by whitequark** [comment]
There is no example repo linked.

**Comment by flaviens** [comment]
Sorry :disappointed: , edited the post

**Comment by whitequark** [comment]
No, you did not do anything wrong. I broke one of the CXXRTL output modes in the `master` branch.

**Comment by whitequark** [comment]
Actually, everything works for me when I build the `master` branch, and `performer` is not a part of the 0.37 release. I believe the problem is on your side.

**Comment by whitequark** [comment]
I think you need to completely uninstall your Yosys reinstallation, rebuild Yosys from scratch from a fresh repo and reinstall it.

**Comment by flaviens** [comment]
Indeed it is fixed now. Thank you very much @whitequark for your support!
