### ISSUE TITLE
synthesis bug as terminate called after throwing an instance of 'std::length_error'

### ISSUE THREAD

**Issue by yelen103** [YosysHQ/yosys#4259]
### Version

 Yosys 0.37+1 (git sha1 e1f4c5c9cbb, clang  -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

Comprehensive rlt.v
The specific steps are in the ‘yosys.log’ in the attachment.

### Expected Behavior

No error message pops up during synthesis

### Actual Behavior

An error is reported and is stored in `yosys_stderr.log`. The synthesis will continue after a period of time.
[yosys_2.zip](https://github.com/YosysHQ/yosys/files/14496504/yosys_2.zip)

**Comment by KrystalDelusion** [comment]
This is the same issue as https://github.com/YosysHQ/yosys/issues/4160 and is fixed in the latest releases. Running the code locally with latest Yosys I do not get any error.
