### ISSUE TITLE
opt_demorgan usage?

### ISSUE THREAD

**Issue by Kmanfi** [YosysHQ/yosys#426]
You search **coarse** cells $reduce_and and $reduce_or.
```
	if( (cell->type != "$reduce_and") && (cell->type != "$reduce_or") )
		return;
```
and then
`//See if this bit is driven by a $not cell
`
but you expect gate to be tech mapped?
`if(x.port == "\\Y" && x.cell->type == "$_NOT_")`

Is it idea to keep reduce cells as coarse and techmap only $not cells?

@azonenberg

**Comment by lethalbit** [comment]
The `help opt_demorgan` output reads:
```
This pass pushes inverters through $reduce_* cells if this will reduce the
overall gate count of the circuit
```

This pass applies [De Morgan's laws](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) to the design which can reduce `!A || !B` to `A && B` or `!A && !B` to `A || B` removing the superfluous not gates reducing the overall gate count of the design.
