### ISSUE TITLE
latch inferred in synthesis process

### ISSUE THREAD

**Issue by cemery123** [YosysHQ/yosys#4276]
### Version

 Yosys 0.37+1 (git sha1 e1f4c5c9cbb, clang  -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

read_verilog rtl.v; synth; write_verilog -noattr syn.v

### Expected Behavior

synthesis successful and write_verilog syn.v

### Actual Behavior

Abnormal crash in synthesis process and failed. I have attacthed the log file
[pending.zip](https://github.com/YosysHQ/yosys/files/14572834/pending.zip)

**Comment by KrystalDelusion** [comment]
I believe this is the same issue as #4160 and is fixed in the latest releases.  Running the code locally with latest Yosys I do not get any error.
