### ISSUE TITLE
Bit-width type conversion causes array overflow

### ISSUE THREAD

**Issue by cemery123** [YosysHQ/yosys#4277]
### Version

 Yosys 0.37+1 (git sha1 e1f4c5c9cbb, clang  -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

read_verilog reduce.v
synth

### Expected Behavior

success synthesis

### Actual Behavior

synthesis failed and if you comment line 175 it will be normal we think it may caused by complexity bits operation. 
[pending-2.zip](https://github.com/YosysHQ/yosys/files/14573822/pending-2.zip)

**Comment by KrystalDelusion** [comment]
See #4276
