### ISSUE TITLE
Crash in yosys-abc

### ISSUE THREAD

**Issue by maliberty** [YosysHQ/yosys#4352]
### Version

Yosys 0.40 (git sha1 a1bb0255d, g++ 8.5.0 -fPIC -Os)

### On which OS did this happen?

Linux

### Reproduction Steps

The problem is reported in https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/issues/1953 which steps to reproduce in ORFS.

@povik may look at this but I opened it here to (1) track it in yosys and (2) in case someone else has time to look at it.

### Expected Behavior

No crash

### Actual Behavior

Crash with 
```
yosys-abc: src/map/scl/sclBufSize.c:388: abc::Abc_Obj_t* abc::Abc_SclAddOneInv(abc::Bus_Man_t*, abc::Abc_Obj_t*, abc::Vec_Ptr_t*, float): Assertion `LoadNew - Load < 1 && Load - LoadNew < 1' failed.
Aborted (core dumped)
```

**Comment by povik** [comment]
Likely fix at berkeley-abc/abc#319
