### ISSUE TITLE
Nothing of abc folder contents at git clone https://github.com/YosysHQ/yosys.git

### ISSUE THREAD

**Issue by ysd375** [YosysHQ/yosys#4394]
### Version

current version

### On which OS did this happen?

Linux

### Reproduction Steps

When I git clone, there is no content in the abc folder.

So it raised an error such as a following picture.
![2024-05-12 192947](https://github.com/YosysHQ/yosys/assets/94088834/52d63bf3-443b-425a-b94d-78329c47e03e)

I think it is wrong something git branch.
Main page shows that like
"abc @ 237d813    Add YosysHQ/abc as a submodule located in abc    4 days ago"

at main branch.

![2024-05-12 192728](https://github.com/YosysHQ/yosys/assets/94088834/9eef50af-c7a8-4395-a1b7-984555270855)

Please check it.

### Expected Behavior

when I git clone it, it will exist the abc folder contents.

### Actual Behavior

Nothing of abc folder contents at git clone of main branch.

**Comment by KrystalDelusion** [comment]
You need to call `git submodule update --init` in the Yosys directory, as the error in your image says. Check out [git submodules documentation](https://git-scm.com/book/en/v2/Git-Tools-Submodules) if you want to learn more about submodules.
