### ISSUE TITLE
Stub RTL Generation Feature

### ISSUE THREAD

**Issue by Peter-Herrmann** [YosysHQ/yosys#4442]
### Feature Description

Designs frequently need to stub out modules to simplify simulation or synthesis during development. As part of workflows, it is very useful to be able to automatically generate stub modules from design files.
 
I would like to request a feature where Yosys can "stub-out" a module, similar to `blackbox` but with the ability to tie outputs to 
default values.

**Bare Minimum Features**

- Remove all internal logic (like `blackbox`)
- Tie all outputs to zero

**Nice-to-have Features**

- Configurable stub output behavior:
  - Selectively assign constants to outputs
  - Pass-through ports
  - Flop (N-cycle delay)

For example, to create a stub module for a module `foo`:
```
module foo (
    input  wire A_i,
    output wire B_o
);

    assign B_o = ~A_i;

endmodule
```
One could read in the file and use a command:
```
yosys> stub -set B_o 1 foo
```
Which would generate a module similar to this:
```
/* Generated by Yosys 0.39+147 (git sha1 0a854cf4c, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

(* src = "foo.v:1.1-8.10" *)
module foo(A_i, B_o);
  (* src = "foo.v:2.17-2.20" *)
  input A_i;
  wire A_i;
  (* src = "foo.v:3.17-3.20" *)
  output B_o;
  wire B_o;
  assign B_o = 1'b1;
endmodule
```
Note the following differences from blackbox modules:
- Stub modules would not be marked with `blackbox` or `cells_not_processed` attributes
- All outputs are assigned

**Comment by widlarizer** [comment]
Can you further describe your use case? Is this not feasible to do and control in your sources?

**Comment by povik** [comment]
@Peter-Herrmann From a preliminary discussion we are unlikely to support a full-fledged `stub` command which would provide all of the nice-to-have features.

**Comment by povik** [comment]
@Peter-Herrmann From a preliminary discussion we are unlikely to support a full-fledged stub command which would provide all of the nice-to-have features. Some elementary stubbing can be achieved with existing Yosys commands, and those we can extend if there's an important omission, but once the stubbing involves the generation of non-trivial logic, we prefer users write HDL for those cases over a specialized `stub` command.

That being said I think you should be able to stub-out `foo` and connect the `B_o` output to a constant with the following:

    delete top/* top/x:* %d
    connect -set B_o 0 foo

The first command deletes everything but the ports. The second connects a constant. I am not sure if there's a command to create a pass-through.

**Comment by Peter-Herrmann** [comment]
The same effect could be achieved in the source code with the preprocessor, but that has a few problems at scale. 

- For very large designs, this can be extremely tedious, and custom automation scripts are the usual solution. Instead of everyone having custom scripts to automate stub generation, it would be nice to have at least one popular tool that has a natively supported solution.
- It is often necessary to stub out third party IPs that we do not want to modify directly (wrappers can achieve this, but it clutters the design hierarchy and can introduce breaking changes to existing testbenches)
- It can dramatically decrease readability of source files, especially for large designs with many ports. Having every module come with stubbing-out lines could as much as double the size of the code base.
- Having a tool to generate stubs procedurally reduces maintenance (port changes don't need to be changed in every configuration) and reduces surface area for bugs.

**Comment by Peter-Herrmann** [comment]
> once the stubbing involves the generation of non-trivial logic, we prefer users write HDL for those cases over a specialized `stub` command.

I think this is a very reasonable stance.

> Some elementary stubbing can be achieved with existing Yosys commands

I will try this out, this may be enough for my needs. Thank you!

**Comment by povik** [comment]
I noticed I have mistyped the sample commands (the module name would be `foo` not `top`), see now
