### ISSUE TITLE
Build issue with abc submodule

### ISSUE THREAD

**Issue by gussmith23** [YosysHQ/yosys#4481]
### Version

Happening on the most recent commit, as well as commits from May and March

### On which OS did this happen?

Linux

### Reproduction Steps

Build Yosys on Ubuntu 20.04 with gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0.

### Expected Behavior

Yosys builds successfully.

### Actual Behavior

I see the following errors:

```
/usr/bin/ld: src/sat/glucose/Options.o: relocation R_X86_64_32 against symbol `_ZGVZN3abc5Gluco6Option13getOptionListEvE7options' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: src/sat/glucose/SimpSolver.o: relocation R_X86_64_32S against symbol `_ZTVN3abc5Gluco10SimpSolverE' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: src/sat/glucose/System.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: src/sat/glucose2/Glucose2.o: relocation R_X86_64_32S against symbol `_ZTVN3abc6Gluco26SolverE' can not be used when making a PIE object; recompile with -fPIE
...
```

This feels like it must be on my side, because I've never seen this before and it seems to be happening on every commit I try!

**Comment by jix** [comment]
IIRC I had similar issues when my abc directory had a mix of object files, some compiled with abc's default build configuration and some with the build configuration used by yosys's makefile when building abc. If this is the same issue that should get fixed when cleaning the abc build artifacts by running `make clean-abc` in the yosys directory.

**Comment by gussmith23** [comment]
Thanks, yeah, i just deleted my entire Yosys checkout and re-cloned. That fixed it.

Thanks Jannis!
