### ISSUE TITLE
Consider adding a Dockerfile to make it easier to build required image

### ISSUE THREAD

**Issue by dkarchmer** [YosysHQ/yosys#466]
Docker would allow people to build the code without having to worry about installing all the required dependencies.

This will also make it easy to migrate to different build systems, many which support Docker these days.

**Comment by 1138-4EB** [comment]
This might be useful to you: https://github.com/1138-4EB/elide/tree/master/docker

**Comment by cliffordwolf** [comment]
WIP: https://hub.docker.com/r/openfpga/icetools/

**Comment by hutch31** [comment]
Used the attached Vagrant configuration to successfully build and install yosys, useful if your native platform is non-Linux.

[yosys_vagrant.zip](https://github.com/YosysHQ/yosys/files/1750137/yosys_vagrant.zip)

**Comment by abdelrahmanhosny** [comment]
@cliffordwolf the WIP link is not working. Have you managed to get a release of it?

**Comment by daveshah1** [comment]
A Dockerfile has been added in #829
