### ISSUE TITLE
Any link_design equivalent or alternative?

### ISSUE THREAD

**Issue by redpanda3** [YosysHQ/yosys#4660]
### Link to page

https://github.com/vortexgpgpu/vortex/blob/master/hw/syn/yosys/synth.sh#L31

### Issue

Hi, I saw a yosys file using the following
```
link_design  -top module
```
But yosys currently doesn't have this command, what is the updated alternative? I cannot find any clue in documentation.

Best,
redpanda.

**Comment by donn** [comment]
`hierarchy -top module`

**Comment by redpanda3** [comment]
thanks donn
