### ISSUE TITLE
Incomplete Warning Messages After Yosys Synthesis

### ISSUE THREAD

**Issue by jiangshuirou** [YosysHQ/yosys#4710]
### Version

Yosys 0.39+165

### On which OS did this happen?

Linux

### Reproduction Steps

Hello, when using Yosys to synthesize an rtl.v file, during the synthesis phase, the port clk[0] in the module15 is either unconnected or has no load. Yosys should ideally issue a corresponding warning for this situation. (There are a total of 6 such warning messages, with detailed explanations provided in the attachment.)
[Relevant_documents.zip](https://github.com/user-attachments/files/17646901/Relevant_documents.zip)

### Expected Behavior

Yosys issues the following warning messages:
1、Port clk[0] in module module15 is either unconnected or has no load 
2、 Port wire17[8] in module module15 is either unconnected or has no load 
3、Port wire17[4] in module module15 is either unconnected or has no load 
4、Port clk[0] in module module15 is either unconnected or has no load 
5、 Port wire17[8] in module module15 is either unconnected or has no load 
6、Port wire17[4] in module module15 is either unconnected or has no load 

### Actual Behavior

The Yoysy warning messages did not include the above-expected 6 warning messages.

**Comment by KrystalDelusion** [comment]
Yosys doesn't lint. Use verilator or something else if you need longing features. See #4705
