### ISSUE TITLE
dfflibmap does not honor dont_use attribute

### ISSUE THREAD

**Issue by hutch31** [YosysHQ/yosys#472]
When using a liberty file where certain cells have a "dont_use : true;" attribute set on them, yosys does not honor the attribute and uses the marked cells.

**Comment by cliffordwolf** [comment]
What version of Yosys are you using? Support for `dont_use` has been added two and a half years ago in 522705cc (2015-05-31). Please post an example liberty file that demonstrates the issue if you are using a version newer than that.

**Comment by hutch31** [comment]
The version I am using is 8e22e811.  I later looked through the source and saw that dont_use support is present; naturally the library I compiled against is proprietary so I cannot submit it.  I will try to create a synthetic test case that reproduces this.

**Comment by hutch31** [comment]
Unable to reproduce, will re-open if I can create a test case.
