### ISSUE TITLE
ERROR: Assert `refcount_modules_ == 0' failed in kernel/rtlil.cc:401

### ISSUE THREAD

**Issue by mubes** [YosysHQ/yosys#481]
Hi,

Probably sticky fingers again on my part, but with current git (26c4323d4860c936f6699375167a02b66b38118d as of 6th Jan 22:54 GMT) I get the above error with the following code;

```
module topLevel (
		 input clkIn,
		 output clkOut
		 );

   
 // Set up clock for 48Mhz with input of 12MHz
   SB_PLL40_CORE #(
		   .FEEDBACK_PATH("SIMPLE"),
		   .PLLOUT_SELECT("GENCLK"),
		   .DIVR(4'b0000),
		   .DIVF(7'b0111111),
		   .DIVQ(3'b100),
		   .FILTER_RANGE(3'b001)
		   ) uut (
			  .LOCK(lock),
			  .RESETB(1'b1),
			  .BYPASS(1'b0),
			  .REFERENCECLK(clkIn),
			  .PLLOUTCORE(clkOut)
			  );
endmodule
```

when run through yosys with;

`yosys -p "synth_ice40 -blif tlt.blif" tlt.v`

This came up in a much more extensive project, I've tried to pare it down to the minimum that still creates the issue.  Still a newbie at all this, so apologies if I've done something silly.  VERY VERY appreciative of this fine code and it's associates (icestorm, arachne-pnr).

(The code compiles without error on 0.7 release BTW)

Regards

DAVE

**Comment by cliffordwolf** [comment]
Oops. :) Fixed in 446ccf1f05b2b36db9161bf4ab050778a1cbaee6.
