### ISSUE TITLE
Mac OS X strip -d causes install to fail.

### ISSUE THREAD

**Issue by derekmulcahy** [YosysHQ/yosys#489]
On Mac OS X High Sierra a `make install` fails with the message

`strip -d /usr/local/bin/yosys
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: no files specified`

This is because the Xcode version of strip does something strange when passed the -d flag. The -S flag is equivalent and should work on both Linux and OS X.

The change which caused this was part of https://github.com/YosysHQ/yosys/commit/57e02b662906f80ae43445a328c5476d1b92bd60

**Comment by cliffordwolf** [comment]
Changed it to `-S` in 318be86. Thanks for looking into the issue and suggesting a fix.
