### ISSUE TITLE
SMTBMC: Assume A on posedge clk and assert A together fail

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#491]
I would expect assume(A) and assert(A) to succeed.  However, if (A) is assumed on the positive edge of a clock, as is necessary in order to use $past, then it's possible for the assert(A) to fail if asserted independent of a clock.

See https://zipcpu.com/tmp/ybuga.tgz for a minimal example.

Dan

**Comment by cliffordwolf** [comment]
That's because in the last cycle there is no clockedge yet that triggers the assumption. This is a common problem when mixing clocked assumptions and unclocked assertions. Run `chformal -assume -early` to make the assumption not wait for a clock edge. (Don't mix this with `clk2fflogic` though.)
