### ISSUE TITLE
Attribute at always statement.

### ISSUE THREAD

**Issue by Kmanfi** [YosysHQ/yosys#496]
Hi, please run read_verilog for code below.
```
module attrib_test (clk, d, q);
   input clk;
   input d;
   output q;
   reg q_o;
   always (*test*) @(posedge clk) 
     begin
	q_o <= d;
     end
   assign q = q_o;
endmodule

```

**Comment by Kmanfi** [comment]
Tested this with Modelsim. vlog compiles it.

**Comment by cliffordwolf** [comment]
That's not an attribute on the always block. An attribute on the always block would need to be present *before* the always statement. See this syntax from IEEE Std. 1364-2001:

![image](https://user-images.githubusercontent.com/619764/35331755-c826b504-0108-11e8-999b-880a0f05bdbf.png)

**Comment by Kmanfi** [comment]
Ok. Thank you. Just wondering why Modesim compiles it. Closing this.
