### ISSUE TITLE
ABC has moved.

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#517]
The ABC project has [moved from bitbucket](https://bitbucket.org/alanmi/abc) to [github](https://github.com/berkeley-abc/abc).  This breaks the master yosys makefile, which references a hard URL for ABC.  Further, ABC is also no longer maintained under mercurial.  It is now under git source code control.  A quick examination suggests that only the main Makefile needs to be patched, although the patch required is a touch more intrusive than just changing URL to the new location.

**Comment by cliffordwolf** [comment]
Thanks! I'll fix this right away.

**Comment by mithro** [comment]
OMG! This is awesome!

**Comment by cliffordwolf** [comment]
Fixed in 6f681c4.

**Comment by zeldin** [comment]
So maybe we can have a new release with this fix in it soon?  It's been a while since 0.7, and now it doesn't even build anymore...  :wink:

**Comment by cliffordwolf** [comment]
@zeldin Uh! Yeah. That's a really good point.. I'll make a new release some time in May.
