### ISSUE TITLE
sat -dump_vcd, $end fix for $timescale.

### ISSUE THREAD

**Issue by Kmanfi** [YosysHQ/yosys#520]
Hi I tried to convert -dump_vcd generated VCD file with Modelsim's vcd2wlf.
To make it work, it needs $end for $timescale. I propose following fix to file sat.cc.

```
fprintf(f, "$timescale 1ns\n"); // arbitrary time scale since actual clock period is unknown/unimportant
—> fprintf(f, "$end\n");
fprintf(f, "$scope module %s $end\n", module->name.c_str());
```

**Comment by cliffordwolf** [comment]
Removed the timescale altogether (in commit 665eec3). Why set it to an arbitrary value if we can also just not set it at all.
