### ISSUE TITLE
dont_use attribute ignored

### ISSUE THREAD

**Issue by hutch31** [YosysHQ/yosys#527]
## Steps to reproduce the issue

unzip dont_use.zip [dont_use.zip](https://github.com/YosysHQ/yosys/files/1877822/dont_use.zip)
sh testcase

## Expected behavior

This synthetic test case was created to reproduce an issue found with a proprietary library file.  I edited the osu018_stdcells file to remove

 the flop the design uses by default.

Edited osu018_stdcells has dont_use : true attribute added to DFFSR cell.  Resulting netlist should not contain DFFSR.

## Actual behavior

Netlist contains two DFFSR cells, grep prints fail if cells occur in output netlist.

**Comment by cliffordwolf** [comment]
Thanks! Fixed in 705c366.
