### ISSUE TITLE
verific license question

### ISSUE THREAD

**Issue by OrDavidi** [YosysHQ/yosys#540]
Hi Guys
I wish to use verific as a frontend for yosys.
I wonder if i need the : 
1.  "RTL elaboration" license
2. Simple parsing license is enough and yosys doing the elaboration by itself ? 
By reading the verific frontend code it seems that verific already "boolianized" the RTL so it is probably option 1.

Thanks!

**Comment by cliffordwolf** [comment]
Yes, you need an "RTL elaboration" license.
