### ISSUE TITLE
Patch: Support more character literals

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#542]
Yosys does not currently support all of the required string literal characters.  IEEE Std 1800-2012, 5.9.1, states that \v, \f, and \a are to be supported.  These are characters not currently supported by yosys.  The [attached patch](https://github.com/YosysHQ/yosys/files/1968475/yosys-lexpatch.txt) adds support for these characters as well as support for the carriage return character.

Dan

**Comment by cliffordwolf** [comment]
Thanks! Merged in e060375.
