### ISSUE TITLE
The ABCURL in Makefile of Yosys

### ISSUE THREAD

**Issue by pasandi20** [YosysHQ/yosys#543]
## Steps to reproduce the issue

*Provide instructions for reproducing the issue. Make sure to include
all neccessary source files. (You can simply drag&drop a .zip file into
the issue editor.)*

## Expected behavior

*Please describe the behavior you would have expected from the tool.*

## Actual behavior

*Please describe how the behavior you see differs from the expected behavior.*

**Important Note:** Nobody will be able to help you and/or fix the issue if you
do not provide sufficient information for reproducing the problem.

**Comment by cliffordwolf** [comment]
This was fixed in Yosys git head the same day they moved to github.
