### ISSUE TITLE
Yosys isn't able to import it's own eblif output format?

### ISSUE THREAD

**Issue by mithro** [YosysHQ/yosys#565]
## Steps to reproduce the issue

 * Generate an eblif with `.cname` or `.conn` values in the output
 * Try and import the file into yosys with `read_blif`
 * Get `Syntax Error` message.

## Expected behavior

 * Be able to read the eblif file into yosys (for simulation / equivalence checking).

**Comment by litghost** [comment]
This can be closed with #596 pulled.

**Comment by mithro** [comment]
BTW Do we have any tests for "round tripping via blif"?

**Comment by mithro** [comment]
Happy to close this issue and open a seperate one for that....
