### ISSUE TITLE
Sync reset

### ISSUE THREAD

**Issue by Kmanfi** [YosysHQ/yosys#566]
## Steps to reproduce the issue

```
module sync_reset_test(clk, rst, d, z);
      input clk, rst, d;
      output z;

  test_m #() my_m (
      .clk(clk),
      .arst(1'b1),
      .srst(rst),
      .d(d),
      .z(z)
    );
endmodule

module test_m (clk, arst, srst, d, z);

    input   clk;
    input   arst;
    input   srst;
    input   d;
    output  z;

    reg     q_reg;

    assign z = q_reg;

        //always @(posedge clk or posedge arst)
        always @(posedge clk or negedge arst)
        if (arst == 1'b0)
        begin
            q_reg  <= 1'b0;
        end
        else if (srst == 1'b1)
        begin
            q_reg  <= 1'b0;
        end
        else
        begin
            q_reg  <= d;
        end

endmodule
```
```
read_verilog ...
prep

```
## Expected behavior
Expect to have $dff with $mux.

## Actual behavior
Result is $adff with $mux.

Another note:
This alternative "always" with "posedge" will give you this. 
ERROR: Async reset \arst yields non-constant value 1'm for signal \q_reg.

**Comment by cliffordwolf** [comment]
> Result is $adff with $mux.

This is exactly the behavior that IEEE Std. 1364.1(E):2002 mandates.

> Expect to have $dff with $mux.

This would be in violation of IEEE Std. 1364.1(E):2002.

> This alternative "always" with "posedge" will give you this.  
> ERROR: Async reset \arst yields non-constant value 1'm for signal \q_reg.

This would not be a valid way to model a storage alement according to IEEE Std. 1364.1(E):2002 (see sect. 5.2). So the error message is justified.
