### ISSUE TITLE
Need a serials of stable version for packaging.

### ISSUE THREAD

**Issue by sequencer** [YosysHQ/yosys#609]
Hello, I wanna package yosys for Arch Linux in community db. And I noticed that since yosys 0.7, stable version disappeared ;(. So if it is possible for yosys to bring back stable versions?

**Comment by sequencer** [comment]
And by the way, if I'd like to create a pr to dynamically link `libabc.so`, would it be ok?

**Comment by cliffordwolf** [comment]
> So if it is possible for yosys to bring back stable versions?

We are working on it.

> And by the way, if I'd like to create a pr to dynamically link libabc.so, would it be ok?

`LINK_ABC` is for embedded targets. On regular builds Yosys should not link against abc at all, neither statically nor dynamically, but instead just call an external ABC binary. The `ABCEXTERNAL` build variable can be used to set the name of this binary (on debian it is `berkeley-abc` afair).

**Comment by sequencer** [comment]
Thank you!
Looking forward to next stable release! ;)

**Comment by sequencer** [comment]
ping,
any progress yet?

**Comment by daveshah1** [comment]
Yosys 0.8 has been released now.
