### ISSUE TITLE
Block RAM inference with negedge clock generates code that can't place

### ISSUE THREAD

**Issue by wd5gnr** [YosysHQ/yosys#615]
always @(posedge clka)
  begin
     if (wen) mem[addra]]<=dina; 
   end
always @(negedge clka)
   begin
      doutb<=mem[addrb];
   end

This generates a BLIF, but archane-PNR says:
demo.blif:2026: fatal error: unknown formal `RCLKN'

Looking in the BLIF this is -- no surprise -- in the SB_RAM40_4KNR macro.

**Comment by daveshah1** [comment]
This works fine for me with latest Yosys and arachne-pnr, are you sure you are using the latest git versions of each (and not whatever archaeological version distribution packages tend to be)?

If this still doesn't work, please provide a full synthesisable example and the exact commands you are running so it can be investigated further.

**Comment by wd5gnr** [comment]
Wow, that was fast. This is with the latest Yosys, but I have not updated Arachne is a while. I will have a look. Thanks.

**Comment by wd5gnr** [comment]
Yes, sorry. Updating Arachne did the trick. My bad.

**Comment by daveshah1** [comment]
No problem! Glad it is working now
