### ISSUE TITLE
Documentation Glitch

### ISSUE THREAD

**Issue by wd5gnr** [YosysHQ/yosys#621]
## Steps to reproduce the issue
Visit http://www.clifford.at/yosys/documentation.html

## Expected behavior

The description for attrvcp should be on the same line as the entry. Other subsequent entries (e.g., check or cd) should be on the same lines with their descriptions.

## Actual behavior

 Instead, the attrvcp description is on the next command and this continues to the end of the file.

Not sure if this is a glitch in the source of this or just the web page or whatever.

**Comment by cliffordwolf** [comment]
LGTM
![image](https://user-images.githubusercontent.com/619764/54384337-44823980-4694-11e9-981a-7806451c0f4b.png)
