### ISSUE TITLE
Quoting for hierarch -libdir name

### ISSUE THREAD

**Issue by wd5gnr** [YosysHQ/yosys#632]
I am trying to write a more or less general-purpose driver for yosys and related tools and I ran into a quirk. Here's an excerpt of what I have:

LADIR="/path/to/some/library/directory"
. . .
yosys -p "read_verilog \"$FN.v\" ; hierarchy -libdir . ; hierarchy -libdir $LADIR ; synth_ice40 -blif \"$FN.blif\""

This works. However, if LADIR has a space it it, it fails. Of course. You need quotes around it. However, quoting it JUST LIKE the $FN.v and $FN.blif strings causes failure:

The error occurs during 4.2 and says (with some quotes removed):

ERROR: Module topxxx referenced in module top in cell xxx is not part of the design.

However, if the file has no spaces and there is no quoting around $LADIR then it works fine.

**Comment by cliffordwolf** [comment]
`hierarchy -libdir "$LADIR"` should just work. (That's a feature added in 21a1cc1b6 in 2015. But I added a bugfix in 1cd04a6 just now for the case where the closing `"` is immediately followed by `;`.)

In your particular case you would need to make sure that the UNIX shell is not consuming the quotation marks. So you'd have to for example write `yosys -p "... hierarchy -libdir \"$LADIR\"; ..."` when calling yosys from a shell script. Without a MCVE to reproduce the issue that's my best guess for why this isn't working for you.
