### ISSUE TITLE
Yosys does not support $changed

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#644]
$changed(X) is defined in SVA to be equivalent to (A != $past(A));

## Steps to reproduce the issue

The following code,

    always @(posedge i_clk)
    if (f_past_valid)
        assert($changed(X) == (X != $past(X));

will cause Yosys to fail with an error, "Can't resolve function name '\$changed'."

## Expected behavior

The example above should compile and pass without problems.

## Actual behavior

See above.

## Proposed solution

See the attached patch for a solution to this issue.

[patch.txt](https://github.com/YosysHQ/yosys/files/2434665/patch.txt)

Does this mean I [now (finally) qualify for guru status](https://twitter.com/zipcpu/status/1002566775484092416)?

**Comment by cliffordwolf** [comment]
> See the attached patch for a solution to this issue.

Applied in 62424ef.

> Does this mean I now (finally) qualify for guru status?

You already have that status. See e060375.  :)
