### ISSUE TITLE
issue trying to prove equivalency with equiv_struct

### ISSUE THREAD

**Issue by rafaeltp** [YosysHQ/yosys#682]
I am trying to prove equivalency with a blackbox submodule and found a somewhat weird behavior.
There are also considerable differences between older commits and HEAD.

## Steps to reproduce the issue

a.v:
```
module a(input a, input b, output c, output d);
wire g;
add add(.a(a), .b(b), .c(c), .d(g));
assign d = g & 1;
endmodule
```

b.v:
```
module a(input a, input b, output c, output d);
wire f;
add add(.a(a), .b(b), .c(c), .d(f));
assign d = f & 1;
endmodule
```

run:
```
yosys -p "read_verilog -sv ./a.v; hierarchy -auto-top; rename -top gold; design -stash gold; read_verilog -sv ./b.v; hierarchy -auto-top; rename -top gate; design -stash gate; design -copy-from gold -as gold gold; design -copy-from gate -as gate gate; equiv_make gold gate equiv; hierarchy -top equiv; flatten; equiv_simple; equiv_struct; equiv_simple;  equiv_status;"
```

## Expected behavior

All equiv cells proven.

## Actual behavior

```
Unproven $equiv $auto$equiv_make.cc:241:find_same_wires$4: \d_gold \d_gate
```

Now the part that I think is weirder is using a.v as gold and gate (simple net name change)

1) successful verification in Yosys 0.7+681 (git sha1 ed1f0b25, clang 6.0.1 -fPIC -Os)
2) fails in Yosys 0.8+23 (git sha1 db676957, clang 6.0.1 -fPIC -Os)

I am not sure this is intended behavior that got fixed recently or not. 
However, it would be nice to be able to structurally verify in both cases (same and different net names).

**Comment by cliffordwolf** [comment]
The problem is that `add` is not even a proper blackbox module, because Yosys doesn't know which ports are in- and which are outputs.

Add something like the following `add.v`:

```
(* blackbox *)
module add(input a, input b, input c, output d);
endmodule
```

And then run `read_verilog add.v` before `equiv_make`. Then it works fine:

```
$ yosys -p "read_verilog -sv ./a.v; hierarchy -auto-top; rename -top gold; design -stash gold; read_verilog -sv ./b.v; hierarchy -auto-top; rename -top gate; design -stash gate; design -copy-from gold -as gold gold; design -copy-from gate -as gate gate; read_verilog add.v; equiv_make gold gate equiv; hierarchy -top equiv; flatten; equiv_simple; equiv_struct; equiv_simple;  equiv_status;"

...

13. Executing EQUIV_STATUS pass.
Found 2 $equiv cells in equiv:
  Of those cells 2 are proven and 0 are unproven.
  Equivalence successfully proven!
```
