### ISSUE TITLE
What does ice40_opt -unlut do? 

### ISSUE THREAD

**Issue by qaarah** [YosysHQ/yosys#683]
Hi, 
The documentation states that using ice40_opt with -unlut option,  this command will transform all already mapped SB_LUT4 cells back to logic. 
What does that mean? Does this command reverse the technology mapping?  
I use this command to replace SB_LUT4 in my blif file because for equivalence checking (using abc) does not have the gate library SB_LUT4. That is the error I get when I call yosys-abc for cec.   
Does the .blif file generated using this command is technology mapped? 

Thanks

**Comment by cliffordwolf** [comment]
> What does that mean?

It means it replaces the `SB_LUT4` cells in the design with equivalent `$lut` cells.
