### ISSUE TITLE
Liberty file parser: improved newline handling.

### ISSUE THREAD

**Issue by trcwm** [YosysHQ/yosys#685]
`library(test)`
`{`
makes the liberty parser/lexer exit prematurely without generating an error. 

The liberty manual states the opening { of a group should appear on the same line as the group name. However, the liberty file format does not have a formal definition AFAIK. I think many tools accept the non-standard newline. ABC certainly does this.

IMO, if Yosys considers this an error, it should be reported to the user, or, if it is not considered an error, the parser/lexer should be changed to accept the alternate syntax.

**Comment by cliffordwolf** [comment]
I'm assuming this has been fixed in 04cd179 via #687.
