### ISSUE TITLE
Liberty file / DFFLIBMAP pass: generate error on missing/undefined pins.

### ISSUE THREAD

**Issue by trcwm** [YosysHQ/yosys#686]
The DFFLIBMAP pass tries to find flip-flops with the right combination of reset, preset and next_state expressions. When these expressions reference an undefined pin, the liberty parser/lexer or DFFLIBMAP do not report an error but silently ignore the cell.

It would be beneficial to report this condition to the user.

**Comment by cliffordwolf** [comment]
Thanks! Merged #687.
