### ISSUE TITLE
$rose() and $fell() are defined on the LSB of their arguments only

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#689]
## Steps to reproduce the issue

In the following example, both assertions should fail.

    (* anyseq *) reg [1:0] X;
    always @(posedge i_clk)
    if (f_past_valid)
    begin
        assert($rose(X) == ((X)&&(!$past(X)));
        assert($fell(X) == ((!X)&&($past(X)));
    end

Values causing them to fail should include the sequence 2'h0, 2'h2 for rose, and 2'h2, 2'h0 for fell.

## Expected behavior

According to the SVA 2012 specification, section 16.9.3 Sampled Value Functions, page 361,

- $rose returns true if the LSB of the expression changed to 1.  Otherwise, it returns false.
- $fell returns true if the LSB of the expression changed to 0.  Otherwise it returns false.

## Actual behavior

Frontends/ast/simplify.cc tests the entire value against zero, rather than just the LSB.

See this pull request for a suggested change: [#688](https://github.com/YosysHQ/yosys/pull/688)

**Comment by cliffordwolf** [comment]
Thanks! Merged #688.
