### ISSUE TITLE
make test: Intermittent failure of tests/realmath test

### ISSUE THREAD

**Issue by DiodeRed** [YosysHQ/yosys#698]
I was building the current (5387ccb041f4acafc96c7b3fcf8db04dddfb8ab5) version of yosys and decided to run "make test".

The test was being run with a local build of the latest iverilog from git (36120769432577e3abd12a182b97d605bd4572a6) and I received the following error for a test failure one time.

```
cd tests/realmath && bash run-test.sh ""
generating tests..
running tests..
[0][1][2][3][4][5][6][7][8][9][10][11][12][13][14][15][16][17][18][19][20][21][22]
 67: 0000000000000000000000000000000000000000000000011000101100000111 0000000000000000000000000000000000000000000000010000000000000000
                                                     ^   ^ ^^     ^^^                                                 ^   ^ ^^     ^^^
```

For some reason, upon simply re-running "make test", this error went away, and I haven't been able reproduce it since, but I thought it was worth reporting anyway, just in case.

**Comment by cliffordwolf** [comment]
Fixed in the crudest way possible in 9820ed6.
