### ISSUE TITLE
Design which works with Vivado fails with Yosys+Vivado

### ISSUE THREAD

**Issue by mithro** [YosysHQ/yosys#711]
## Steps to reproduce the issue

```shell
git clone https://github.com/mithro/litex-buildenv-arty-yosys-xilinx
# Run with Yosys + Vivado
./build_top.sh
# Run with just Vivado
./build_top-v.sh
```

This should produce both a `top.bit` and `top.bin` which can be programmed with whatever method you like. Using openocd it would be something like;
```shell
openocd -f board/digilent_arty.cfg -c "init; pld load 0 top.bit; exit"
```

Connect using your favorite terminal emulator to the correct serial port. With Vivado, the system should boot up and show the LiteX BIOS. With Yosys nothing seems to happen.

The design as an lm32 CPU and an external DDR controller. It should boot a BIOS, train the memory and then wait for firmware to be loaded from either SPI flash or via the USB serial port.

If you compare to `min` branch which has a CPU and no DDR controller. It should work both with Vivado and Yosys.

It is unclear what version of Yosys I was using for this. I will try and reproduce with the latest Yosys and report back.

**Comment by whitequark** [comment]
It is impossible to act on this issue. For one, it is not even clear that this is a Yosys issue. Does the design work correctlyin simulation?

**Comment by mithro** [comment]
@whitequark - The design works correctly in Vivado and similar designs both work correctly in Verilator.

**Comment by mithro** [comment]
@enjoy-digital is investigating further in https://github.com/enjoy-digital/litex/issues/132

**Comment by ZipCPU** [comment]
I spent a lot of time digging into this issue, and I'm going to throw in the towel: the information presented above is not sufficient for finding the problem.  I would need to spend months of time on this design, one that I'm not familiar with, to find this problem.  That's doable, but I'm not funded for that much work.

A second problem is that I do not have the ability at my desk to verify your claims.  Is there a way you can get the design to fail in a post-place-and-route simulation when using yosys while succeeding when using Vivado?

Proper engineering practice requires dividing a design in parts and then identifying which remaining component has a bug, and then repeating until the problem can be found.  This particular design, as presented, no longer has the original designer's conceptual information within it to make this possible.  It appears to be computer generated--meaning that the task would be easier to do by whomever has the higher level language information.

I'm going to recommend @cliffordwolf close this issue for these reasons.

**Comment by whitequark** [comment]
I emphatically agree with everything @ZipCPU said here.
