### ISSUE TITLE
typo in frontends/ilang/ilang_lexer.l ?

### ISSUE THREAD

**Issue by janrinze** [YosysHQ/yosys#754]
While compiling the file ilang_parser.tab.hh could not be found.
Seems the file reference should be ilang_parser.tab.h if i am correct.
The patch below is from my change which seems to do the trick.
If other people have seen this issue you can use the patch below.

diff --git a/frontends/ilang/ilang_lexer.l b/frontends/ilang/ilang_lexer.l
index d8e01ae4..84238854 100644
--- a/frontends/ilang/ilang_lexer.l
+++ b/frontends/ilang/ilang_lexer.l
@@ -30,7 +30,7 @@
 #endif
 
 #include "frontends/ilang/ilang_frontend.h"
-#include "ilang_parser.tab.hh"
+#include "ilang_parser.tab.h"
 
 USING_YOSYS_NAMESPACE

**Comment by daveshah1** [comment]
My understanding is that this is not a typo, but some files changed names recently. Running `make clean` and then trying to build again should solve your build issue.
