### ISSUE TITLE
Btor backend seems to lose logic for (* keep *) signals

### ISSUE THREAD

**Issue by makaimann** [YosysHQ/yosys#767]
## Summary

When a signal is marked with (* keep *) and assigned to, it seems that the btor back-end keeps the wire but loses the logic. 

## Steps to reproduce the issue

Files: [reproduce-issue.zip](https://github.com/YosysHQ/yosys/files/2713075/reproduce-issue.zip)

* Unzip
* Run `yosys -s simple.ys`

## Expected behavior

Because of the line: `assign eq_a_b = (num_a == num_b);`, I would expect `eq_a_b` to be driven and to see the btor keyword `eq` in the produced btor. Furthermore, I would expect the `eq_a_b` signal to actually be equivalent to `num_a == num_b`.

## Actual behavior

It seems that the btor backend does not recognize that `eq_a_b` is driven and thus fails to produce the btor. I can of course get around this by using `setundef` but then `eq_a_b` is still not assigned to. If you make the signal a primary output, then everything works as expected of course. However, there are cases where it would be nice to keep a wirename without making it an output.

##
Hopefully I've explained the issue thoroughly enough and please let me know if I can provide any more information/help.

Thanks for your time and all your work on Yosys!

**Comment by cliffordwolf** [comment]
Oops. Fixed in 0a840dd.
