### ISSUE TITLE
Make test Fails at svinterfaces

### ISSUE THREAD

**Issue by Kish0re7** [YosysHQ/yosys#840]
cd tests/svinterfaces && bash run-test.sh ""
Test: svinterface1 -> Segmentation fault (core dumped)
mv: cannot stat 'output.txt': No such file or directory
Segmentation fault (core dumped)
mv: cannot stat 'output.txt': No such file or directory
diff: reference_result.txt: No such file or directory
diff: dut_result.txt: No such file or directory
ERROR!
Test: svinterface_at_top -> Segmentation fault (core dumped)
mv: cannot stat 'output.txt': No such file or directory
Segmentation fault (core dumped)
mv: cannot stat 'output.txt': No such file or directory
diff: reference_result.txt: No such file or directory
diff: dut_result.txt: No such file or directory
ERROR!
Makefile:570: recipe for target 'test' failed
make: *** [test] Error 255

please help me to get rid of this problem..
Thanks

**Comment by cliffordwolf** [comment]
Insufficient information to reproduce the issue. It works here (Ubuntu 18.04):

```
clifford@euler:~/Work/yosys$ cd tests/svinterfaces/
clifford@euler:~/Work/yosys/tests/svinterfaces$ bash run-test.sh 
Test: svinterface1 -> ok
Test: svinterface_at_top -> ok
```

And it also works in Travis CI.

**Comment by BharathS11** [comment]
Same error.
Fresh install of ubuntu 18.04 on a virtual machine. Building yosys from git. Fails on svinterfaces test.
I have the crash dump, if it can help.

Thanks

**Comment by mmicko** [comment]
@BharathS11 Make sure you are using latest iverilog, packaged one is very old version, you take get sources for latest one from : https://github.com/steveicarus/iverilog

**Comment by BharathS11** [comment]
@mmicko That was it. Thanks
