### ISSUE TITLE
missing glob.h on TerMux on Android

### ISSUE THREAD

**Issue by programmerjake** [YosysHQ/yosys#863]
## Steps to reproduce the issue

Try to build in TerMux.
## Expected behavior

builds successfully

## Actual behavior

fails since android doesn't have glob.h until api level 28 (Android Pie).

It would be nice to have an option to disable glob support when glob.h is not detected.

**Comment by cliffordwolf** [comment]
d9bb5f3 adds an `ENABLE_GLOB` makefile option.
