### ISSUE TITLE
Regression when initial-ising reg used on negedge clock

### ISSUE THREAD

**Issue by eddiehung** [YosysHQ/yosys#873]
## Steps to reproduce the issue

The following emits `Warning: Wire $paramod\template\neg_clk=1.q has an unprocessed 'init' attribute.` on: 44a44a0 but works on e112d2fb

```
module template (input clk, input d, output reg q);
parameter neg_clk = 0;

initial q = 1'b1;

generate
    if (neg_clk) begin
        always @(negedge clk) q <= d;
    end
    else begin
        always @(posedge clk) q <= d;
    end
endgenerate
endmodule

module top(input clk, input d, output [1:0] q);
    template #(.neg_clk(1)) neg_clk(clk, d, q[0]);
    template #(.neg_clk(0)) pos_clk(clk, d, q[1]);
endmodule
```
when `./yosys -q -p 'synth_xilinx; flatten; dump top' init.v`

## Expected behavior

Expect negedge warning to not get emitted, and the netlist to have both flops have INIT value of 1'b1

## Actual behavior

Fails for negedge case.
Works for posedge case.

negedge case worked on e112d2fb (i.e. INIT value is correct, and no warning emitted)

**Comment by cliffordwolf** [comment]
Explanation: commit 3090951d5 added the Xilinx `*_1` FF cell variants (as alternative to using the `IS_C_INVERTED` parameter), and switched the default behavior for FF mapping to use them, but didn't add them to the `dffinit` call. This has been fixed in 8c0740b. cc @litghost
