### ISSUE TITLE
Yosys fails to ignore $readmemh call in generate block to non-existant file

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#886]
## Steps to reproduce the issue

Consider the following code:

```
module	nofile(i_v, o_v);
	parameter	N=4;
	parameter	LUTFILE="";
	parameter [0:0]	FLAG = 1;
	input	wire	[N-1:0]	i_v;
	output	reg		o_v;

	reg	[0:0]	luttbl	[0:(1<<N)-1];
	integer	k;

	generate if (FLAG)
	begin

		initial if (LUTFILE)
			$readmemh(LUTFILE, luttbl);
		else begin
			for(k=0; k<(1<<N); k=k+1)
				luttbl[k] = ^k;
		end

		always @(*)
			o_v = luttbl[i_v];
	end else begin

		always @(*)
			o_v = 1'b0;

	end endgenerate
endmodule
```

Notice the parameter, LUTFILE, that would nominally contain a filename for $readmemh.  As set, this parameter is empty.  I've tried setting it to `""` or even `0` with the same effect.  If there's no intermediate generate, the behavior is as I would expect: the file is not read, $readmemh is not called, and yosys doesn't complain about the $readmemh call with a missing file.  However, when I add in the intermediate generate based upon the 1-bit FLAG, things change.

To see this, I run yosys with

    yosys -q -p 'read -formal nofile.v; prep -top nofile'

and now it fails with: `ERROR: Can not open file .. for \$readmemh'.

## Expected behavior

I expect that the `if` within the generate block should keep the $readmemh from being executed, and thus from failing due to a missing file.  This works fine if there's no generate block for FLAG (not shown above), but fails when this block is added.

## Actual behavior

I'm probably being redundant by now, but what's actually happening is that I get an error due to a missing file that yosys wasn't supposed to try to read in the first place.

**Comment by lethalbit** [comment]
As of Yosys 0.20 no error is produced from this test case.
