### ISSUE TITLE
ECP5: Unprocessed init attribute

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/yosys#887]
## Steps to reproduce the issue

For the following code snippet:

```
module mcve(i_clk, o_v);
	input	wire		i_clk;
	output	reg	[3:0]	o_v;

	initial	o_v = 0;
	always @(posedge i_clk)
	begin
		o_v <= 0;
		o_v[2:0] <= o_v[2:0] + 1;
	end

endmodule
```

Run,

```
  yosys -p 'synth_ecp5 -top mcve' mcve.v 
```

## Expected behavior

This code should build with no warnings.

## Actual behavior

Yosys returns the following warning:

```
Warning: Wire mcve.o_v has an unprocessed 'init' attribute.
```

Dan

**Comment by daveshah1** [comment]
This isn't ECP5 specific, synth_ice40 and synth_xilinx appear to give the same behaviour. I think it's more of a general issue as to how init attributes should be dealt with when we optimise away flops.
