### ISSUE TITLE
Relaxing of newline results in strict ';' need

### ISSUE THREAD

**Issue by Fatsie** [YosysHQ/yosys#894]
In 04cd179 newline handling was relaxed but it results in more strict need of ';' usage.
I have a .lib file from TSMC where not each line ends in ; and this now fails in yosys, e.g.

    cell (XXX) {
      ...
      area : 87.5
      cell_footprint : "XXX"
      pin (A1) {
      ...
    }

Reverting 04cd179 makes the TSMC .lib work again.

**Comment by trcwm** [comment]
TSMC is using a incorrect .lib syntax 😃 Will fix asap.

**Comment by Fatsie** [comment]
BTW, culprit is likely Library Compiler of Synopsys itself. The std. cell lib also includes 'compiled' liberty files with .db extension. This means they went through the Synopsys Library Compiler without problem.

**Comment by Fatsie** [comment]
I can confirm #897 works with the TSMC liberty file.
