### ISSUE TITLE
rtlil.cc code review.

### ISSUE THREAD

**Issue by RonxBulld** [YosysHQ/yosys#970]
https://github.com/YosysHQ/yosys/blob/314ff1e4ca00ef8024bbb0d2f031efd78b01f9a1/kernel/rtlil.cc#L3459

if (chunks_.size() != chunks_.size())
maybe
if (chunks_.size() != other.chunks_.size())
???

**Comment by cliffordwolf** [comment]
Ooops. Thanks for reporting this issue! Fixed in 9268cd1.

Modulo hash collisions it's "just" a performance bug. I guess that's why this wasn't found earlier.
