### ISSUE TITLE
INIT attribute not set on FDRE when shift register inference

### ISSUE THREAD

**Issue by eddiehung** [YosysHQ/yosys#982]
## Steps to reproduce the issue

`yosys -p "synth_xilinx; dump t:FDRE" lfsr_24.v`

```
module lfsr_24 (input clk, output dout);
  reg [24:1] state = 24'b0;
  always @(posedge clk)
    state <= { state[24-1:1], state[24] ~^ state[23] ~^ state[22] ~^ state[17] };
  assign dout = state[24];
endmodule
```

## Expected behavior

`FDRE` to have `INIT` parameter set to `1'b0`

## Actual behavior

`FDRE` has `INIT` parameter set to `1'bx`
```
<<SNIP>>
  cell \FDRE $auto$simplemap.cc:420:simplemap_dff$18.fpga_srl_1
    parameter \INIT 1'x
    connect \C \clk
    connect \CE 1'1
    connect \D $auto$simplemap.cc:420:simplemap_dff$18.T0
    connect \Q \state [16]
    connect \R 1'0
  end
<<SNIP>>
```
Works when shift register inference disabled (`synth_xilinx -nosrl`).
Could this be related to #956 (though there are no warning messages as that issue has)

But I did notice this:
```
2.27. Executing DFFINIT pass (set INIT param on FF cells).
Setting lfsr_24.$auto$simplemap.cc:420:simplemap_dff$18.fpga_srl_1.INIT (port=Q, net=\state [16]) to 1'x.
Setting lfsr_24.$auto$simplemap.cc:420:simplemap_dff$40.INIT (port=Q, net=\state [22]) to 1'0.
Setting lfsr_24.$auto$simplemap.cc:420:simplemap_dff$41.INIT (port=Q, net=\state [23]) to 1'0.
Removing init attribute from wire lfsr_24.state.
Removed 0 unused cells and 47 unused wires.
```

**Comment by eddiehung** [comment]
Issue appears to be that `shregmap` will set away the `(* init *)` attribute on signals that it infers into a shift register to `1'bx`. However, our tech mapping rules can sometimes blow these inferred shift registers back into flops, and when it does that, a subsequent `dffinit` will init those registers at `1'bx`... (even if I have instantiated a tech specific cell (e.g. `FDRE`))

Number of solutions:
- `shregmap` to now blow away `(* init *)` attribute
- `dffinit` to not overwrite cells with `INIT` already set with new `1'bx` value.

Am thinking latter...

**Comment by cliffordwolf** [comment]
\o/

```
  cell \FDRE $auto$simplemap.cc:420:simplemap_dff$17.fpga_srl_1
    parameter \INIT 1'0
    connect \C \clk
    connect \CE 1'1
    connect \D $auto$simplemap.cc:420:simplemap_dff$17.T0
    connect \Q \state [16]
    connect \R 1'0
  end
```
